import type { EventCharacter } from "../types";

// Curated fancy-dress / character pack for Indian school events.
// All ideas are intentionally simple, household-friendly and time-bound.
// Speeches are kept short (2–3 lines) so a 4–10-yr child can memorise easily.

export const EVENT_CHARACTERS: EventCharacter[] = [
  // ── Independence Day (15 Aug) ───────────────────────────────────────────────
  {
    id: "bhagat-singh",
    category: "independence-day",
    character: "Bhagat Singh",
    emoji: "🧔🏻‍♂️",
    tagline: "Brave young revolutionary",
    timeMinutes: 25,
    difficulty: "Easy",
    accent: ["#f97316", "#fde047"],
    lowCost: true,
    materials: [
      "Yellow / mustard kurta or shirt",
      "Yellow turban or yellow cloth (1 m)",
      "Black moustache (drawn or stick-on)",
      "Toy gun or rolled paper baton (optional)",
    ],
    steps: [
      "Dress the child in a mustard kurta-pyjama (or yellow shirt with brown pants).",
      "Tie the yellow cloth as a turban — keep one corner falling on the shoulder.",
      "Draw a small handlebar moustache with eye-pencil.",
      "Add the toy gun in one hand for the classic look.",
    ],
    speech:
      "I am Bhagat Singh. I gave my life for India's freedom. Inquilab Zindabad — long live the revolution!",
    speechShort: "I am Bhagat Singh. I love my India. Inquilab Zindabad!",
  },
  {
    id: "subhash-chandra-bose",
    category: "independence-day",
    character: "Subhash Chandra Bose",
    emoji: "🧑🏻‍✈️",
    tagline: "Netaji — leader of the INA",
    timeMinutes: 30,
    difficulty: "Medium",
    accent: ["#16a34a", "#facc15"],
    materials: [
      "Olive-green / khaki shirt and pants",
      "Brown belt",
      "Round black-framed glasses",
      "Military-style cap (or a folded khaki cloth)",
    ],
    steps: [
      "Dress the child in a khaki shirt tucked in with matching pants.",
      "Tighten with a brown belt — keep the look crisp.",
      "Add the round glasses and the cap.",
      "Practise a confident salute pose for the speech.",
    ],
    speech:
      "I am Netaji Subhash Chandra Bose. Give me blood, and I shall give you freedom! Jai Hind!",
    speechShort: "I am Netaji. Tum mujhe khoon do, main tumhe azaadi dunga. Jai Hind!",
  },
  {
    id: "rani-lakshmibai",
    category: "independence-day",
    character: "Rani Lakshmibai",
    emoji: "👸🏻",
    tagline: "Warrior queen of Jhansi",
    timeMinutes: 30,
    difficulty: "Medium",
    accent: ["#dc2626", "#fbbf24"],
    materials: [
      "Maroon or red kurta + churidar",
      "Yellow/red dupatta tied as a sash",
      "Toy sword",
      "Bindi and a small crown / tiara",
    ],
    steps: [
      "Dress the child in red kurta with churidar.",
      "Drape the dupatta diagonally and tie at the waist as a sash.",
      "Place a small crown / tiara on the head and add a red bindi.",
      "Hold the toy sword in the right hand for the warrior pose.",
    ],
    speech:
      "I am Rani Lakshmibai of Jhansi. Main apni Jhansi nahi doongi! I fought bravely for my motherland.",
    speechShort: "I am Rani Lakshmibai. Main apni Jhansi nahi doongi!",
  },
  {
    id: "freedom-fighter-girl",
    category: "independence-day",
    character: "Freedom Fighter (Girl)",
    emoji: "🥻",
    tagline: "Tricolour saree look",
    timeMinutes: 20,
    difficulty: "Easy",
    accent: ["#f97316", "#22c55e"],
    lowCost: true,
    materials: [
      "White kurta or top",
      "Tricolour dupatta or any green/orange/white dupatta",
      "Small Indian flag",
      "Plain hair with two braids",
    ],
    steps: [
      "Dress the child in a plain white kurta.",
      "Drape the tricolour dupatta across one shoulder.",
      "Braid the hair into two simple plaits.",
      "Hand over a small Indian flag for the photo.",
    ],
    speech:
      "I am a freedom fighter. My country India is the greatest! Vande Mataram. Jai Hind!",
  },

  // ── Republic Day (26 Jan) ───────────────────────────────────────────────────
  {
    id: "dr-apj-abdul-kalam",
    category: "republic-day",
    character: "Dr. APJ Abdul Kalam",
    emoji: "👨🏽‍🔬",
    tagline: "Missile Man of India",
    timeMinutes: 20,
    difficulty: "Easy",
    accent: ["#0ea5e9", "#fbbf24"],
    lowCost: true,
    materials: [
      "Grey or white shirt",
      "Black pants",
      "Hair brushed forward (Kalam-style)",
      "A book in hand (optional)",
    ],
    steps: [
      "Dress the child in a plain grey or white shirt with black pants.",
      "Comb the hair forward and slightly tousled — Kalam's signature look.",
      "Hand a book or a small toy rocket as a prop.",
      "Practise a smiling, kind expression.",
    ],
    speech:
      "I am Dr. APJ Abdul Kalam, the Missile Man of India. Dream big, work hard — you can do anything!",
    speechShort: "I am Dr. Kalam. Dream big and work hard!",
  },
  {
    id: "indian-soldier",
    category: "republic-day",
    character: "Indian Soldier",
    emoji: "🪖",
    tagline: "Brave army jawan",
    timeMinutes: 25,
    difficulty: "Easy",
    accent: ["#15803d", "#65a30d"],
    materials: [
      "Olive green / camouflage shirt and pants",
      "Black belt and black shoes",
      "Toy gun",
      "Soldier cap (or olive scarf)",
    ],
    steps: [
      "Dress the child in olive-green shirt + camouflage pants.",
      "Add a black belt and tuck the shirt in for a smart look.",
      "Place the cap firmly. Practise a sharp salute.",
      "Hold the toy gun across the chest for photos.",
    ],
    speech:
      "I am an Indian Army soldier. I protect my country day and night. Jai Hind! Bharat Mata ki Jai!",
  },
  {
    id: "dr-bhimrao-ambedkar",
    category: "republic-day",
    character: "Dr. B.R. Ambedkar",
    emoji: "📘",
    tagline: "Father of the Indian Constitution",
    timeMinutes: 25,
    difficulty: "Easy",
    accent: ["#1d4ed8", "#0284c7"],
    materials: [
      "Blue suit / blazer with white shirt",
      "Red or blue tie",
      "Round black-framed glasses",
      "A book (representing the Constitution)",
    ],
    steps: [
      "Dress the child in a blue blazer over a white shirt.",
      "Add the tie — keep it neat and short.",
      "Put on the round glasses.",
      "Hold the book proudly in both hands.",
    ],
    speech:
      "I am Dr. Bhimrao Ambedkar. I wrote India's Constitution to give every Indian equal rights. Jai Bhim!",
  },

  // ── Gandhi Jayanti (2 Oct) ──────────────────────────────────────────────────
  {
    id: "mahatma-gandhi",
    category: "gandhi-jayanti",
    character: "Mahatma Gandhi",
    emoji: "🧓🏻",
    tagline: "Father of the Nation",
    timeMinutes: 20,
    difficulty: "Easy",
    accent: ["#ca8a04", "#fef3c7"],
    lowCost: true,
    materials: [
      "White cloth or bedsheet (2 m) — for dhoti",
      "Round wire-frame glasses",
      "Bald cap or skin-coloured swim cap (optional)",
      "Walking stick / wooden stick",
    ],
    steps: [
      "Wrap the white cloth around the waist as a dhoti — knee length.",
      "Drape another small white cloth on one shoulder.",
      "Place the round glasses on the nose and the bald cap on top.",
      "Hand the walking stick — practise a slow, steady walk.",
    ],
    speech:
      "I am Mahatma Gandhi. I believe in truth and non-violence. Be the change you wish to see in the world!",
    speechShort: "I am Gandhi ji. I love peace and truth.",
  },
  {
    id: "kasturba-gandhi",
    category: "gandhi-jayanti",
    character: "Kasturba Gandhi",
    emoji: "👵🏻",
    tagline: "Ba — Gandhi ji's brave wife",
    timeMinutes: 25,
    difficulty: "Easy",
    accent: ["#d97706", "#fde68a"],
    materials: [
      "Plain white saree (or white dupatta + white skirt)",
      "Small bindi",
      "Simple bun hairstyle",
      "Khadi shawl (optional)",
    ],
    steps: [
      "Dress the child in a plain white saree drape (or skirt + dupatta look).",
      "Make a small bun at the back of the head.",
      "Add a small bindi on the forehead.",
      "Drape the khadi shawl across both shoulders.",
    ],
    speech:
      "I am Kasturba Gandhi. I stood with Bapu in his fight for India's freedom. Satya aur Ahimsa — truth and non-violence!",
  },

  // ── Annual Day ──────────────────────────────────────────────────────────────
  {
    id: "krishna",
    category: "annual-day",
    character: "Lord Krishna",
    emoji: "🪈",
    tagline: "Mischievous flute-playing god",
    timeMinutes: 30,
    difficulty: "Medium",
    accent: ["#7c3aed", "#facc15"],
    materials: [
      "Yellow dhoti + yellow scarf",
      "Peacock-feather mor-pankh on a small crown",
      "Bansuri (toy flute)",
      "Blue face paint (optional)",
    ],
    steps: [
      "Wrap the yellow dhoti at the waist; drape the scarf across one shoulder.",
      "Place the small crown with peacock feather on top of the head.",
      "Apply a hint of blue face paint on cheeks (very light).",
      "Hand the flute and practise the classic flute-playing pose.",
    ],
    speech:
      "I am Lord Krishna. I love butter, music and friends. Always smile and spread joy!",
    speechShort: "I am Krishna. I play the flute and love everyone!",
  },
  {
    id: "fairy",
    category: "annual-day",
    character: "Fairy",
    emoji: "🧚‍♀️",
    tagline: "Sparkly little fairy",
    timeMinutes: 20,
    difficulty: "Easy",
    accent: ["#ec4899", "#a78bfa"],
    materials: [
      "Pink or purple frock",
      "Stick-on fairy wings (or DIY card-paper wings)",
      "Magic wand (stick + paper star + glitter)",
      "Hairband with stars",
    ],
    steps: [
      "Dress the child in the pink/purple frock.",
      "Attach the wings to the back using elastic loops.",
      "Place the hairband on the head.",
      "Hand over the magic wand — practise a graceful twirl.",
    ],
    speech:
      "I am a sparkly fairy. With one wave of my wand I make wishes come true. Sprinkle kindness everywhere!",
  },
  {
    id: "santa",
    category: "annual-day",
    character: "Santa Claus",
    emoji: "🎅",
    tagline: "Christmas Santa for winter shows",
    timeMinutes: 15,
    difficulty: "Easy",
    accent: ["#dc2626", "#ffffff"],
    materials: [
      "Red shirt + red pants (or red kurta)",
      "Cotton wool for the beard",
      "Red Santa cap",
      "Small gift bag",
    ],
    steps: [
      "Dress the child entirely in red.",
      "Stick cotton wool with double-sided tape to make a fluffy beard.",
      "Top it off with a Santa cap.",
      "Carry a small jute bag of sweets / chocolates.",
    ],
    speech:
      "Ho Ho Ho! I am Santa Claus. I bring gifts and joy to every child. Merry Christmas to all!",
    speechShort: "Ho Ho Ho! Merry Christmas! I am Santa.",
  },

  // ── General Fancy Dress — Animals ───────────────────────────────────────────
  {
    id: "lion",
    category: "fancy-dress",
    character: "Lion",
    emoji: "🦁",
    tagline: "King of the jungle",
    timeMinutes: 25,
    difficulty: "Easy",
    accent: ["#f59e0b", "#b45309"],
    materials: [
      "Brown / yellow t-shirt and shorts",
      "Yellow chart paper for the mane",
      "Face paint (brown + black)",
      "Brown tail (cloth strip)",
    ],
    steps: [
      "Cut the chart paper into long strips and stick them to a hairband for the mane.",
      "Dress the child in the brown / yellow tee + shorts.",
      "Paint a small black nose, whiskers and brown spots on cheeks.",
      "Pin the cloth tail at the back.",
    ],
    speech:
      "Roar! I am the lion, king of the jungle. I am strong, brave and fearless!",
    speechShort: "Roar! I am the lion. I am the king of the jungle!",
  },
  {
    id: "peacock",
    category: "fancy-dress",
    character: "Peacock",
    emoji: "🦚",
    tagline: "National bird of India",
    timeMinutes: 30,
    difficulty: "Medium",
    accent: ["#0e7490", "#16a34a"],
    materials: [
      "Blue / green t-shirt and pants",
      "Green & blue chart paper / coloured paper for tail feathers",
      "Glitter and stick-on eyes for feathers",
      "Yellow card paper for beak",
    ],
    steps: [
      "Cut large feather shapes from chart paper. Add eye stickers.",
      "Stick the feathers in a fan shape on a card-paper backing.",
      "Tie the fan to the back with elastic loops.",
      "Make a small yellow beak headband.",
    ],
    speech:
      "I am the peacock, the national bird of India. My feathers shine with all the colours of the rainbow!",
  },
  {
    id: "rabbit",
    category: "fancy-dress",
    character: "Rabbit",
    emoji: "🐰",
    tagline: "Cute hopping bunny",
    timeMinutes: 15,
    difficulty: "Easy",
    accent: ["#f9a8d4", "#fce7f3"],
    lowCost: true,
    materials: [
      "White t-shirt and pants",
      "Hairband with white card-paper ears",
      "Cotton ball for the tail",
      "Pink face paint for nose & whiskers",
    ],
    steps: [
      "Cut two long ear shapes from white card paper, stick on a hairband.",
      "Dress the child in white from top to bottom.",
      "Pin a cotton ball at the back as the bunny tail.",
      "Paint a pink nose and 3 whiskers on each cheek.",
    ],
    speech:
      "I am a fluffy little rabbit. I love carrots and hopping around the garden. Hop hop hop!",
    speechShort: "I am a bunny. I love carrots. Hop hop hop!",
  },

  // ── General Fancy Dress — Professions ───────────────────────────────────────
  {
    id: "doctor",
    category: "fancy-dress",
    character: "Doctor",
    emoji: "🩺",
    tagline: "Helps people stay healthy",
    timeMinutes: 15,
    difficulty: "Easy",
    accent: ["#0284c7", "#bae6fd"],
    lowCost: true,
    materials: [
      "White shirt or oversized white kurta (lab-coat substitute)",
      "Toy stethoscope (or one drawn on chart paper)",
      "ID card on a lanyard",
      "Notebook + pen",
    ],
    steps: [
      "Dress the child in the white shirt as a lab coat.",
      "Hang the stethoscope around the neck.",
      "Make a quick ID card with name + 'Dr.' written on it.",
      "Hold the notebook to look like a prescription pad.",
    ],
    speech:
      "I am a doctor. I check sick people and give them medicines so they get well soon. Stay safe and healthy!",
  },
  {
    id: "police",
    category: "fancy-dress",
    character: "Police Officer",
    emoji: "👮",
    tagline: "Keeps everyone safe",
    timeMinutes: 20,
    difficulty: "Easy",
    accent: ["#1e3a8a", "#f59e0b"],
    materials: [
      "Khaki / dark blue shirt and pants",
      "Black belt",
      "Police cap (or paper folded into a cap)",
      "Whistle on a string",
    ],
    steps: [
      "Dress the child in the khaki / blue uniform colours.",
      "Add the black belt over the shirt.",
      "Place the police cap on top.",
      "Tie the whistle around the neck.",
    ],
    speech:
      "I am a police officer. I keep our city safe. Always follow rules and stay safe on the road!",
  },
  {
    id: "farmer",
    category: "fancy-dress",
    character: "Farmer",
    emoji: "🧑‍🌾",
    tagline: "Annadata — feeds the nation",
    timeMinutes: 15,
    difficulty: "Easy",
    accent: ["#65a30d", "#ca8a04"],
    lowCost: true,
    materials: [
      "Plain kurta + dhoti (or shirt + folded pyjama)",
      "Cloth tied as a turban (gamcha)",
      "A small toy sickle or stick",
      "A few fake / real wheat stalks (paper roll)",
    ],
    steps: [
      "Dress the child in a simple kurta and dhoti (or pyjama).",
      "Tie the gamcha cloth around the head as a farmer's turban.",
      "Hold the toy sickle in one hand and the wheat stalks in the other.",
      "Smudge a tiny bit of brown make-up on cheeks for a 'sun-kissed' look (optional).",
    ],
    speech:
      "I am a farmer — the Annadata. I work hard in the fields so everyone has food to eat. Jai Jawan, Jai Kisan!",
  },
  {
    id: "teacher",
    category: "fancy-dress",
    character: "Teacher",
    emoji: "👩‍🏫",
    tagline: "Helps us learn every day",
    timeMinutes: 10,
    difficulty: "Easy",
    accent: ["#7c3aed", "#a855f7"],
    lowCost: true,
    materials: [
      "Plain saree or formal kurta",
      "Spectacles",
      "A book and a pencil",
      "Hair tied in a neat bun",
    ],
    steps: [
      "Dress the child in a simple saree or smart kurta.",
      "Tie the hair in a neat bun.",
      "Add the spectacles.",
      "Hold a book in one hand and a long pencil/pointer in the other.",
    ],
    speech:
      "I am a teacher. I help children learn new things every day. Knowledge is the greatest gift!",
  },
  {
    id: "jawaharlal-nehru",
    category: "independence-day",
    character: "Jawaharlal Nehru",
    emoji: "🌹",
    tagline: "Chacha Nehru — first PM of India",
    timeMinutes: 15,
    difficulty: "Easy",
    accent: ["#0ea5e9", "#f3f4f6"],
    lowCost: true,
    materials: [
      "White Nehru jacket (or white kurta + sleeveless waistcoat)",
      "White churidar / pyjama",
      "A red rose to pin on the chest",
      "White Gandhi cap (optional)",
    ],
    steps: [
      "Dress the child in a white kurta and pyjama.",
      "Layer the Nehru jacket on top — keep buttons closed.",
      "Pin the red rose on the left chest pocket.",
      "Add the white cap and practise a kind, friendly smile.",
    ],
    speech:
      "I am Jawaharlal Nehru — Chacha Nehru. I love children, for they are the future of India. Jai Hind!",
    speechShort: "I am Chacha Nehru. Children are India's future. Jai Hind!",
  },
  {
    id: "scientist",
    category: "fancy-dress",
    character: "Scientist",
    emoji: "🔬",
    tagline: "Curious mind, big discoveries",
    timeMinutes: 15,
    difficulty: "Easy",
    accent: ["#0d9488", "#bae6fd"],
    lowCost: true,
    materials: [
      "White shirt or oversized white kurta (lab coat substitute)",
      "Safety glasses or any clear-frame glasses",
      "Notebook + pen",
      "A small flask / bottle as a prop",
    ],
    steps: [
      "Dress the child in the white shirt as a lab coat.",
      "Slip on the glasses.",
      "Carry the notebook in one hand and the flask in the other.",
      "Practise a 'thinking' pose — finger on chin.",
    ],
    speech:
      "I am a scientist. I ask questions, do experiments and discover new things to make the world better!",
  },
  {
    id: "traffic-police",
    category: "fancy-dress",
    character: "Traffic Police",
    emoji: "🚦",
    tagline: "Keeps roads safe & moving",
    timeMinutes: 15,
    difficulty: "Easy",
    accent: ["#1e40af", "#fbbf24"],
    lowCost: true,
    materials: [
      "White shirt + dark blue / khaki pants",
      "Police cap (or paper-folded cap)",
      "Whistle on a string",
      "White gloves (optional)",
    ],
    steps: [
      "Tuck the white shirt into the dark pants.",
      "Place the cap firmly on the head.",
      "Hang the whistle around the neck.",
      "Practise the classic 'stop' and 'go' hand signals.",
    ],
    speech:
      "I am a traffic police officer. I keep our roads safe. Always wear a helmet, follow the signal — red means stop, green means go!",
  },
  {
    id: "shiva",
    category: "annual-day",
    character: "Lord Shiva",
    emoji: "🔱",
    tagline: "The destroyer of evil",
    timeMinutes: 30,
    difficulty: "Medium",
    accent: ["#0369a1", "#f3f4f6"],
    materials: [
      "Tiger-print cloth or orange dhoti",
      "Toy trishul (or DIY from foil + chart paper)",
      "White face powder (for ash effect — vibhuti)",
      "Long beaded mala",
    ],
    steps: [
      "Wrap the tiger-print cloth at the waist as a dhoti.",
      "Lightly dust the white powder on forehead, chest and arms (vibhuti).",
      "Draw 3 horizontal stripes on the forehead with the powder.",
      "Place the mala around the neck and hold the trishul firmly.",
    ],
    speech:
      "I am Lord Shiva. I destroy evil and protect the good. Har Har Mahadev!",
    speechShort: "I am Shiva ji. Har Har Mahadev!",
  },
  {
    id: "tree",
    category: "fancy-dress",
    character: "Tree",
    emoji: "🌳",
    tagline: "Save trees, save Earth",
    timeMinutes: 30,
    difficulty: "Medium",
    accent: ["#15803d", "#a16207"],
    materials: [
      "Brown t-shirt and brown pants",
      "Green chart paper / craft paper for leaves",
      "A few small fake / paper fruits",
      "Brown headband + double-sided tape",
    ],
    steps: [
      "Cut leaf shapes from green chart paper (around 30–40 leaves).",
      "Stick leaves all over a brown t-shirt and on the headband.",
      "Pin a few paper fruits on shoulders / chest.",
      "Practise standing tall and still — like a real tree!",
    ],
    speech:
      "I am a tree. I give you oxygen, fruits and shade. Please save trees and save our Earth!",
    speechShort: "I am a tree. I give you oxygen. Save trees!",
  },
  {
    id: "sun",
    category: "fancy-dress",
    character: "Sun",
    emoji: "☀️",
    tagline: "Light & energy for all",
    timeMinutes: 20,
    difficulty: "Easy",
    accent: ["#f59e0b", "#facc15"],
    lowCost: true,
    materials: [
      "Yellow t-shirt and yellow pants / leggings",
      "Yellow & orange chart paper for sun rays",
      "Headband or thin card-paper crown base",
      "A drawn smiley face on a paper plate (optional centrepiece)",
    ],
    steps: [
      "Cut long triangle 'rays' from yellow + orange paper.",
      "Stick the rays around the headband / crown to make a sun halo.",
      "Dress the child in head-to-toe yellow.",
      "Optional: pin the smiley sun-face plate on the chest.",
    ],
    speech:
      "I am the sun. I give the world light, warmth and energy. Without me, no plant or animal could live!",
    speechShort: "I am the sun. I give light and warmth!",
  },
  {
    id: "astronaut",
    category: "fancy-dress",
    character: "Astronaut",
    emoji: "🧑‍🚀",
    tagline: "Explorer of the stars",
    timeMinutes: 30,
    difficulty: "Medium",
    accent: ["#1e40af", "#94a3b8"],
    materials: [
      "White hoodie / white shirt and pants",
      "Silver foil paper for chest panel",
      "Helmet (toy or made from a transparent box)",
      "ISRO / NASA badge printed on paper",
    ],
    steps: [
      "Dress the child in white from top to bottom.",
      "Stick a small foil panel on the chest with paper buttons drawn on.",
      "Stick the badge on the shoulder.",
      "Carry the helmet under one arm — wear briefly for photos.",
    ],
    speech:
      "I am an astronaut. I fly into space to explore stars and planets. Reach for the stars — anything is possible!",
  },
];
