/**
 * Page-level test for RoutineDetail (src/pages/routines/detail.tsx)
 *
 * Mounts the actual RoutineDetail page component with all external hooks/API
 * calls mocked, feeding it a real school-day routine generated by the rule-based
 * generator. Asserts that:
 * - Recipe & Nutrition cards render for every meal/tiffin item
 * - Slot times match the expected school-day contract
 * - No duplicate meal names
 * - Non-school day produces no Tiffin block
 *
 * @api-lib is resolved via vitest.config.ts alias → artifacts/api-server/src/lib
 * and declared in tsconfig.test.json.
 */

import { describe, it, expect, vi, beforeAll } from "vitest";
import { render, screen } from "@testing-library/react";
import { generateRuleBasedRoutine } from "@api-lib/routine-templates";

vi.mock("wouter", () => ({
  useLocation: () => ["/routines/1", vi.fn()],
  useParams: () => ({ id: "1" }),
  Link: ({ children }: { children: React.ReactNode }) => <a>{children}</a>,
}));

vi.mock("@workspace/api-client-react", () => ({
  useGetRoutine: (_id: number, _opts: unknown) => ({
    data: mockRoutineRef,
    isLoading: false,
    error: null,
  }),
  useGetChild: (_id: number, _opts: unknown) => ({ data: null, isLoading: false }),
  useDeleteRoutine: () => ({ mutate: vi.fn(), isPending: false }),
  getGetRoutineQueryKey: () => [],
  getListRoutinesQueryKey: () => [],
  getGetChildQueryKey: () => [],
}));

vi.mock("@tanstack/react-query", () => ({
  useQueryClient: () => ({ invalidateQueries: vi.fn() }),
  useMutation: (_opts: unknown) => ({ mutate: vi.fn(), isPending: false }),
}));

vi.mock("@/hooks/use-toast", () => ({
  useToast: () => ({ toast: vi.fn() }),
}));

vi.mock("@/hooks/use-auth-fetch", () => ({
  useAuthFetch: () => vi.fn().mockResolvedValue({ ok: false }),
}));

vi.mock("@/lib/api", () => ({
  getApiUrl: (path: string) => path,
}));

vi.mock("@/lib/activity-images", () => ({
  getActivityImage: () => ({ src: "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" }),
}));

vi.mock("@/lib/rewards", () => ({
  addPoints: vi.fn(),
  checkAndAwardBadges: vi.fn().mockReturnValue([]),
  getTotalPoints: vi.fn().mockReturnValue(0),
}));

vi.mock("@/lib/voice", () => ({
  announceCurrentTask: vi.fn(),
  isVoiceEnabled: vi.fn().mockReturnValue(false),
  getVoiceSettings: vi.fn().mockReturnValue({}),
}));

vi.mock("@/components/routine-inline-meals", () => ({
  RoutineInlineMeals: () => null,
}));

vi.mock("@/components/voice-settings", () => ({
  VoiceSettingsPanel: () => null,
}));

vi.mock("@workspace/family-routine", () => ({
  runAdaptiveEngine: vi.fn().mockImplementation((items: unknown[]) => ({
    items: items ?? [],
    changed: false,
    simplified: false,
    suggestion: null,
    summary: {
      delayed: 0,
      adjusted: 0,
      completed: 0,
      skipped: 0,
      completionPct: 0,
      tomorrowTip: "",
    },
  })),
}));

let mockRoutineRef: Record<string, unknown> = {};

const SCHOOL_START = "09:00 AM";
const SCHOOL_END   = "03:00 PM";
const SCHOOL_START_MINS = 9 * 60;
const SCHOOL_END_MINS   = 15 * 60;

function parseMinutes(timeStr: string): number {
  const m = timeStr.match(/(\d+):(\d+)\s*(AM|PM)/i);
  if (!m) return NaN;
  let h = parseInt(m[1], 10);
  const min = parseInt(m[2], 10);
  if (m[3].toUpperCase() === "PM" && h !== 12) h += 12;
  if (m[3].toUpperCase() === "AM" && h === 12) h = 0;
  return h * 60 + min;
}

type RoutineItem = ReturnType<typeof generateRuleBasedRoutine>["items"][number];

function isMeal(i: RoutineItem) {
  return i.category === "meal" || i.category === "tiffin";
}

describe("RoutineDetail page — school day", () => {
  let items: RoutineItem[];

  beforeAll(() => {
    items = generateRuleBasedRoutine({
      childName: "Aarav",
      ageGroup: "early_school",
      wakeUpTime: "07:00 AM",
      sleepTime: "09:00 PM",
      schoolStartTime: SCHOOL_START,
      schoolEndTime: SCHOOL_END,
      hasSchool: true,
      mood: "balanced",
      foodType: "veg",
      region: "pan_indian",
      date: "Monday",
    }).items;

    mockRoutineRef = {
      id: 1,
      childId: 42,
      title: "Aarav — Monday",
      date: new Date().toISOString(),
      items,
    };
  });

  it("renders the page without crashing", async () => {
    const { default: RoutineDetail } = await import("./detail");
    render(<RoutineDetail />);
    expect(document.body).toBeTruthy();
  });

  it("renders a recipe card for every meal/tiffin item", async () => {
    const { default: RoutineDetail } = await import("./detail");
    const { unmount } = render(<RoutineDetail />);
    const mealCount = items.filter(isMeal).length;
    const cards = screen.getAllByTestId("meal-recipe-card");
    expect(cards.length).toBe(mealCount);
    unmount();
  });

  it("Quick Meal Before School is at schoolStart − 15 min (8:45 AM)", () => {
    const meal = items.find((i) => i.category === "meal" && /quick meal/i.test(i.activity));
    expect(meal).toBeDefined();
    expect(parseMinutes(meal!.time)).toBe(SCHOOL_START_MINS - 15);
  });

  it("Tiffin eating block is at schoolStart + 60 min (10:00 AM)", () => {
    const tiffin = items.find((i) => i.category === "tiffin" && i.activity === "Tiffin");
    expect(tiffin).toBeDefined();
    expect(parseMinutes(tiffin!.time)).toBe(SCHOOL_START_MINS + 60);
  });

  it("Lunch is at schoolEnd + 30 min (3:30 PM)", () => {
    const lunch = items.find((i) => i.category === "meal" && /lunch/i.test(i.activity));
    expect(lunch).toBeDefined();
    expect(parseMinutes(lunch!.time)).toBe(SCHOOL_END_MINS + 30);
  });

  it("no duplicate meal/tiffin activity names", () => {
    const names = items.filter(isMeal).map((i) => i.activity);
    expect(new Set(names).size).toBe(names.length);
  });

  it("every meal/tiffin item has recipe and nutrition data attached", () => {
    for (const item of items.filter(isMeal)) {
      expect(item.recipe, `${item.activity} missing recipe`).toBeTruthy();
      expect(item.nutrition, `${item.activity} missing nutrition`).toBeTruthy();
    }
  });
});

describe("RoutineDetail page — non-school day", () => {
  let items: RoutineItem[];

  beforeAll(() => {
    items = generateRuleBasedRoutine({
      childName: "Aarav",
      ageGroup: "early_school",
      wakeUpTime: "07:00 AM",
      sleepTime: "09:00 PM",
      hasSchool: false,
      mood: "balanced",
      foodType: "veg",
      region: "pan_indian",
      date: "Saturday",
    }).items;

    mockRoutineRef = {
      id: 1,
      childId: 42,
      title: "Aarav — Saturday",
      date: new Date().toISOString(),
      items,
    };
  });

  it("renders the page without crashing", async () => {
    const { default: RoutineDetail } = await import("./detail");
    render(<RoutineDetail />);
    expect(document.body).toBeTruthy();
  });

  it("no Tiffin block on a non-school day", () => {
    expect(items.find((i) => i.category === "tiffin")).toBeUndefined();
  });

  it("no Quick Meal Before School on a non-school day", () => {
    expect(items.find((i) => /quick meal/i.test(i.activity))).toBeUndefined();
  });

  it("Breakfast is in 8:00–9:00 AM window", () => {
    const breakfast = items.find((i) => i.category === "meal" && /breakfast/i.test(i.activity));
    expect(breakfast).toBeDefined();
    const mins = parseMinutes(breakfast!.time);
    expect(mins).toBeGreaterThanOrEqual(8 * 60);
    expect(mins).toBeLessThan(9 * 60);
  });

  it("no duplicate meal activity names", () => {
    const names = items.filter(isMeal).map((i) => i.activity);
    expect(new Set(names).size).toBe(names.length);
  });

  it("every meal item has recipe and nutrition data attached", () => {
    for (const item of items.filter(isMeal)) {
      expect(item.recipe, `${item.activity} missing recipe`).toBeTruthy();
      expect(item.nutrition, `${item.activity} missing nutrition`).toBeTruthy();
    }
  });
});
