import { useListRoutines, getListRoutinesQueryKey } from "@workspace/api-client-react";
import { Link } from "wouter";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Calendar, Plus, ChevronRight, Wand2, Sparkles } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";

export default function RoutinesList() {
  const { data: routines, isLoading } = useListRoutines(undefined, {
    query: { queryKey: getListRoutinesQueryKey() }
  });

  return (
    <div className="flex flex-col gap-6 animate-in fade-in duration-500">
      <header className="flex items-center justify-between">
        <div>
          <h1 className="font-quicksand text-3xl font-bold text-foreground">Routines</h1>
          <p className="text-muted-foreground mt-1">Daily schedules generated by AI</p>
        </div>
        <Button asChild className="rounded-full shadow-sm hover-elevate bg-primary text-primary-foreground hover:bg-primary/90">
          <Link href="/routines/generate">
            <Sparkles className="mr-2 h-4 w-4" />
            Generate Routine
          </Link>
        </Button>
      </header>

      {isLoading ? (
        <div className="grid gap-4">
          <Skeleton className="h-24 w-full rounded-2xl" />
          <Skeleton className="h-24 w-full rounded-2xl" />
          <Skeleton className="h-24 w-full rounded-2xl" />
        </div>
      ) : routines && routines.length > 0 ? (
        <div className="grid gap-4">
          {routines.map((routine, index) => (
            <Link key={routine.id} href={`/routines/${routine.id}`}>
              <Card className="rounded-2xl border-border/50 shadow-sm hover:border-primary/30 transition-all cursor-pointer group hover-elevate" style={{ animationDelay: `${index * 50}ms` }}>
                <CardContent className="p-4 sm:p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                  <div className="flex items-center gap-4 w-full">
                    <div className="flex-shrink-0 h-12 w-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                      <Calendar className="h-6 w-6" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="font-quicksand text-lg font-bold text-foreground group-hover:text-primary transition-colors truncate">{routine.title}</h3>
                      <div className="flex flex-wrap items-center gap-2 mt-1 text-sm text-muted-foreground">
                        <span className="inline-flex items-center rounded-md bg-secondary/30 px-2 py-0.5 text-xs font-medium text-secondary-foreground border border-secondary/50">
                          {routine.childName}
                        </span>
                        <span className="flex items-center text-xs">
                          {new Date(routine.date).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                        </span>
                        <span className="text-xs px-2 rounded-full bg-muted">
                          {routine.items?.length || 0} activities
                        </span>
                      </div>
                    </div>
                    <div className="hidden sm:flex items-center justify-center h-10 w-10 rounded-full bg-muted group-hover:bg-primary/10 transition-colors flex-shrink-0">
                      <ChevronRight className="h-5 w-5 text-muted-foreground group-hover:text-primary transition-colors" />
                    </div>
                  </div>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-16 text-center border-2 border-dashed border-border/50 rounded-3xl bg-muted/20">
          <div className="h-16 w-16 bg-primary/10 text-primary rounded-full flex items-center justify-center mb-4">
            <Wand2 className="h-8 w-8" />
          </div>
          <h3 className="font-quicksand text-xl font-bold text-foreground mb-2">No routines yet</h3>
          <p className="text-muted-foreground max-w-sm mb-6">
            Let the AI pediatric coach build a perfect day for your child based on their goals and school times.
          </p>
          <Button asChild size="lg" className="rounded-full shadow-sm hover-elevate">
            <Link href="/routines/generate">
              <Sparkles className="mr-2 h-5 w-5" />
              Generate First Routine
            </Link>
          </Button>
        </div>
      )}
    </div>
  );
}
