/**
 * Integration tests: routine generation → UI rendering
 *
 * These tests call the real `generateRuleBasedRoutine` function (from the API
 * server) and then render the resulting items inside `RoutineItemsPanel` to
 * verify that school-aware meal slots appear at the right times, no meal names
 * are duplicated, and every meal/tiffin block renders a Recipe & Nutrition card.
 *
 * @api-lib is resolved via vitest.config.ts alias → artifacts/api-server/src/lib
 * and declared as a path in tsconfig.test.json so there are no ts-ignore hacks.
 */
import { describe, it, expect, beforeAll } from "vitest";
import { render, screen, within } from "@testing-library/react";
import { RoutineItemsPanel } from "@/test-helpers/RoutineItemsPanel";
import { generateRuleBasedRoutine } from "@api-lib/routine-templates";

// ─── Shared fixtures ──────────────────────────────────────────────────────────

let schoolDayItems: ReturnType<typeof generateRuleBasedRoutine>["items"];
let nonSchoolDayItems: ReturnType<typeof generateRuleBasedRoutine>["items"];

/** Exact school times used in this test suite (deterministic anchors). */
const SCHOOL_START = "09:00 AM";  // 540 min
const SCHOOL_END   = "03:00 PM";  // 900 min

// Derived anchor minutes
const SCHOOL_START_MINS = 9 * 60;    // 540
const SCHOOL_END_MINS   = 15 * 60;   // 900
// Expected anchor times based on applyRoutineV2 contract:
const EXPECTED_QUICK_MEAL_MINS  = SCHOOL_START_MINS - 15;   // 525 → 8:45 AM
const EXPECTED_TIFFIN_MINS      = SCHOOL_START_MINS + 60;   // 600 → 10:00 AM
const EXPECTED_LUNCH_MINS       = SCHOOL_END_MINS   + 30;   // 930 → 3:30 PM

beforeAll(() => {
  schoolDayItems = generateRuleBasedRoutine({
    childName: "Aarav",
    ageGroup: "early_school",
    wakeUpTime: "07:00 AM",
    sleepTime: "09:00 PM",
    schoolStartTime: SCHOOL_START,
    schoolEndTime: SCHOOL_END,
    hasSchool: true,
    mood: "balanced",
    foodType: "veg",
    region: "pan_indian",
    date: "Monday",
  }).items;

  nonSchoolDayItems = generateRuleBasedRoutine({
    childName: "Aarav",
    ageGroup: "early_school",
    wakeUpTime: "07:00 AM",
    sleepTime: "09:00 PM",
    hasSchool: false,
    mood: "balanced",
    foodType: "veg",
    region: "pan_indian",
    date: "Saturday",
  }).items;
});

// ─── Helpers ─────────────────────────────────────────────────────────────────

function parseMinutes(timeStr: string): number {
  const m = timeStr.match(/(\d+):(\d+)\s*(AM|PM)/i);
  if (!m) return NaN;
  let h = parseInt(m[1], 10);
  const min = parseInt(m[2], 10);
  const ampm = m[3].toUpperCase();
  if (ampm === "PM" && h !== 12) h += 12;
  if (ampm === "AM" && h === 12) h = 0;
  return h * 60 + min;
}

function mealItems(items: typeof schoolDayItems) {
  return items.filter((i) => i.category === "meal" || i.category === "tiffin");
}

// ─── School-day rendering tests ───────────────────────────────────────────────

describe("RoutineItemsPanel – school day (generated by real routine generator)", () => {
  it("renders the panel with items from generateRuleBasedRoutine", () => {
    render(<RoutineItemsPanel items={schoolDayItems} />);
    expect(screen.getByTestId("routine-items-panel")).toBeInTheDocument();
  });

  it("contains a 'Quick Meal Before School' activity", () => {
    const found = schoolDayItems.some((i) => i.activity.includes("Quick Meal"));
    expect(found).toBe(true);
  });

  it("Quick Meal Before School is anchored at exactly schoolStart − 15 min (8:45 AM)", () => {
    const meal = schoolDayItems.find((i) => i.activity.includes("Quick Meal"))!;
    expect(meal).toBeDefined();
    expect(parseMinutes(meal.time)).toBe(EXPECTED_QUICK_MEAL_MINS);
  });

  it("contains a Tiffin activity with category = tiffin", () => {
    const tiffin = schoolDayItems.find(
      (i) => i.category === "tiffin" && i.activity === "Tiffin"
    );
    expect(tiffin).toBeDefined();
  });

  it("Tiffin (school break) is anchored at exactly schoolStart + 60 min (10:00 AM)", () => {
    const tiffin = schoolDayItems.find(
      (i) => i.category === "tiffin" && i.activity === "Tiffin"
    )!;
    expect(parseMinutes(tiffin.time)).toBe(EXPECTED_TIFFIN_MINS);
  });

  it("Lunch is anchored at exactly schoolEnd + 30 min (3:30 PM)", () => {
    const lunch = schoolDayItems.find(
      (i) => i.category === "meal" && i.activity.toLowerCase().includes("lunch")
    )!;
    expect(lunch).toBeDefined();
    expect(parseMinutes(lunch.time)).toBe(EXPECTED_LUNCH_MINS);
  });

  it("Drunch is in the 17:00–18:00 window (per applyRoutineV2 contract)", () => {
    const drunch = schoolDayItems.find(
      (i) =>
        i.category === "meal" &&
        /drunch/i.test(i.activity)
    );
    expect(drunch).toBeDefined();
    const mins = parseMinutes(drunch!.time);
    expect(mins).toBeGreaterThanOrEqual(17 * 60);
    expect(mins).toBeLessThanOrEqual(18 * 60);
  });

  it("Dinner is in the 20:00–21:00 window (per applyRoutineV2 contract)", () => {
    const dinner = schoolDayItems.find(
      (i) =>
        i.category === "meal" &&
        /dinner/i.test(i.activity)
    );
    expect(dinner).toBeDefined();
    const mins = parseMinutes(dinner!.time);
    expect(mins).toBeGreaterThanOrEqual(20 * 60);
    expect(mins).toBeLessThanOrEqual(21 * 60);
  });

  it("no duplicate meal/tiffin activity names", () => {
    const names = mealItems(schoolDayItems).map((i) => i.activity);
    expect(new Set(names).size).toBe(names.length);
  });

  it("every meal/tiffin item has recipe and nutrition attached at data level", () => {
    for (const item of mealItems(schoolDayItems)) {
      expect(item.recipe, `${item.activity} missing recipe`).toBeTruthy();
      expect(item.nutrition, `${item.activity} missing nutrition`).toBeTruthy();
    }
  });

  it("every meal/tiffin item renders a Recipe & Nutrition card in the DOM", () => {
    render(<RoutineItemsPanel items={schoolDayItems} />);
    const cards = screen.getAllByTestId("meal-recipe-card");
    expect(cards.length).toBe(mealItems(schoolDayItems).length);
  });

  it("every recipe section shows an Ingredients heading", () => {
    render(<RoutineItemsPanel items={schoolDayItems} />);
    for (const section of screen.getAllByTestId("recipe-section")) {
      expect(within(section).getByText("Ingredients")).toBeInTheDocument();
    }
  });

  it("every nutrition section shows all four macro labels", () => {
    render(<RoutineItemsPanel items={schoolDayItems} />);
    for (const section of screen.getAllByTestId("nutrition-section")) {
      expect(within(section).getByText("Calories")).toBeInTheDocument();
      expect(within(section).getByText("Protein")).toBeInTheDocument();
      expect(within(section).getByText("Carbs")).toBeInTheDocument();
      expect(within(section).getByText("Fat")).toBeInTheDocument();
    }
  });

  it("items are sorted ascending by time", () => {
    let prev = 0;
    for (const item of schoolDayItems) {
      const cur = parseMinutes(item.time);
      if (!isNaN(cur)) { expect(cur).toBeGreaterThanOrEqual(prev); prev = cur; }
    }
  });
});

// ─── Non-school-day rendering tests ───────────────────────────────────────────

describe("RoutineItemsPanel – non-school day (generated by real routine generator)", () => {
  it("renders the panel with items from generateRuleBasedRoutine", () => {
    render(<RoutineItemsPanel items={nonSchoolDayItems} />);
    expect(screen.getByTestId("routine-items-panel")).toBeInTheDocument();
  });

  it("Breakfast is in the 8:00–9:00 AM window", () => {
    const breakfast = nonSchoolDayItems.find(
      (i) =>
        i.category === "meal" &&
        (i.activity.toLowerCase().includes("breakfast") ||
          i.activity.toLowerCase().includes("morning meal"))
    )!;
    expect(breakfast).toBeDefined();
    const mins = parseMinutes(breakfast.time);
    expect(mins).toBeGreaterThanOrEqual(8 * 60);
    expect(mins).toBeLessThanOrEqual(9 * 60);
  });

  it("no Tiffin block on a non-school day", () => {
    expect(nonSchoolDayItems.find((i) => i.category === "tiffin")).toBeUndefined();
  });

  it("no Quick Meal Before School on a non-school day", () => {
    expect(nonSchoolDayItems.find((i) => i.activity.includes("Quick Meal"))).toBeUndefined();
  });

  it("no duplicate meal activity names", () => {
    const names = mealItems(nonSchoolDayItems).map((i) => i.activity);
    expect(new Set(names).size).toBe(names.length);
  });

  it("every meal item has recipe and nutrition attached at data level", () => {
    for (const item of mealItems(nonSchoolDayItems)) {
      expect(item.recipe, `${item.activity} missing recipe`).toBeTruthy();
      expect(item.nutrition, `${item.activity} missing nutrition`).toBeTruthy();
    }
  });

  it("every meal item renders a Recipe & Nutrition card in the DOM", () => {
    render(<RoutineItemsPanel items={nonSchoolDayItems} />);
    const cards = screen.getAllByTestId("meal-recipe-card");
    expect(cards.length).toBe(mealItems(nonSchoolDayItems).length);
  });

  it("Dinner is in the 20:00–21:00 window (per applyRoutineV2 contract)", () => {
    const dinner = nonSchoolDayItems.find(
      (i) =>
        i.category === "meal" &&
        /dinner/i.test(i.activity)
    );
    expect(dinner).toBeDefined();
    const mins = parseMinutes(dinner!.time);
    expect(mins).toBeGreaterThanOrEqual(20 * 60);
    expect(mins).toBeLessThanOrEqual(21 * 60);
  });

  it("items are sorted ascending by time", () => {
    let prev = 0;
    for (const item of nonSchoolDayItems) {
      const cur = parseMinutes(item.time);
      if (!isNaN(cur)) { expect(cur).toBeGreaterThanOrEqual(prev); prev = cur; }
    }
  });
});
