// @workspace/infant-problems
// Research-based static dataset for infant parent problems (0–2 years).
// All content is local — no API calls. Tri-lingual (en / hi / hin) for the
// summary cards. The deep 12-win plans are English-only for now.

export type Lang = "en" | "hi" | "hin";

export interface LocalizedText {
  en: string;
  hi: string;
  hin: string;
}

// ─── Win shape — matches the AI Coach `Win` interface ──────────────────────
export interface InfantWin {
  win: number;
  title: string;
  objective: string;
  deep_explanation: string;
  actions: string[];
  example: string;
  mistake_to_avoid: string;
  micro_task: string;
  duration: string;
  science_reference: string;
}

export interface InfantProblem {
  id: string;
  emoji: string;
  title: LocalizedText;
  description: LocalizedText;     // short one-liner shown on card
  reason: LocalizedText;          // (A) Possible Reason
  solution: LocalizedText[];      // (B) What You Can Do — 2-3 steps
  insight: LocalizedText;         // (C) Amy AI Insight
  reassure: LocalizedText;        // (D) Reassurance line
  rootCause: string;              // root cause shown above the wins
  summary: string;                // 2-sentence overview shown above the wins
  wins: InfantWin[];              // 12 deep, science-backed wins
}

// ─── Compact win helper ────────────────────────────────────────────────────
const w = (
  win: number,
  title: string,
  objective: string,
  deep_explanation: string,
  actions: string[],
  example: string,
  mistake_to_avoid: string,
  micro_task: string,
  duration: string,
  science_reference: string,
): InfantWin => ({
  win, title, objective, deep_explanation, actions, example,
  mistake_to_avoid, micro_task, duration, science_reference,
});

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 1 — BABY NOT SLEEPING
// ═══════════════════════════════════════════════════════════════════════════
const SLEEP_WINS: InfantWin[] = [
  w(1, "Read Your Baby's Wake Windows",
    "Catch the perfect sleep window before overtiredness sets in.",
    "Babies have age-specific awake-time limits (newborn 45–60 min, 4–6 mo 1.5–2 hr, 6–12 mo 2–3 hr). Missing the window spikes cortisol, making sleep dramatically harder.",
    ["Note baby's wake time after every nap.", "Watch for cues 10 min before window closes.", "Begin wind-down before fussiness starts."],
    "Baby woke at 9:00 AM; at 5 months her next nap should start by 10:45 AM.",
    "Waiting for crying — by then she's already overtired.",
    "Set a phone timer for the next wake window today.",
    "1 min",
    "Weissbluth M., Healthy Sleep Habits Happy Child (4th ed., 2015)"),
  w(2, "Build a 4-Step Bedtime Routine",
    "Use repeating cues to trigger the brain's natural melatonin release.",
    "A predictable routine (bath → feed → song → cuddle) becomes a powerful sleep cue. Mindell's 2009 study of 405 mothers showed routine alone reduced night wakings by 50%.",
    ["Choose 4 calm steps and repeat them in the same order nightly.", "Keep the whole routine to 20–30 minutes.", "End in the bedroom with lights low."],
    "Bath at 6:45 → PJ + feed at 7:00 → 1 book at 7:15 → lullaby + crib at 7:25.",
    "Adding new exciting steps each night — kills the sleep cue.",
    "Write your 4 steps on a sticky note tonight.",
    "5 min",
    "Mindell J.A. et al., Sleep (2009) 32(5):599–606"),
  w(3, "Optimize the Sleep Cave",
    "Engineer the room so biology does the work for you.",
    "Pitch dark (blackout curtains), cool 68–72 °F (20–22 °C), and continuous white noise at ~50 dB mimic womb conditions and lower arousal threshold.",
    ["Cover all light leaks — even LED dots.", "Set thermostat 68–72 °F.", "Use a continuous white-noise machine (not loops)."],
    "Black-out curtains + Hatch sound machine on 'rain' at 50 dB across the room.",
    "Bright nightlights or music with songs — both prevent deep sleep.",
    "Walk into baby's room at noon — if you can read, it's too bright.",
    "10 min setup",
    "AAP Safe Sleep Guidelines (2022); Spencer J.A. et al., BMJ (1990)"),
  w(4, "Master the Drowsy-But-Awake Transfer",
    "Let baby fall asleep in the crib so she can return to it on her own.",
    "Sleep cycles end every 45–90 min. If baby fell asleep on you, she wakes confused. Self-settling at the start = self-settling between cycles.",
    ["Watch for sleepy cues, not closed eyes.", "Place baby down with eyes still open.", "Stay calm — pat or shush if needed, but don't pick up."],
    "Eyes heavy at 7:25 — into the crib by 7:27 with a gentle hand on chest.",
    "Always nursing or rocking fully to sleep — guarantees night wakings.",
    "Try one 'drowsy-but-awake' transfer for one nap tomorrow.",
    "10 min",
    "Burnham M.M. et al., J Child Psychol Psychiatry (2002) 43(6):713–725"),
  w(5, "Apply the 5 S's (Newborns 0–4 mo)",
    "Activate the calming reflex with five womb-mimicking sensations.",
    "Dr. Harvey Karp's evidence-based 5 S's (Swaddle, Side/stomach hold, Shush, Swing, Suck) trigger an automatic calming reflex in babies under 4 months.",
    ["Swaddle snug arms-down (legs free).", "Hold on side or stomach in your arms.", "Loud shush + jiggle close to ear, offer pacifier or finger."],
    "Crying baby → swaddled → held on side → shushing in ear → asleep in 60 seconds.",
    "Stopping at one 'S' — the magic is the combination.",
    "Practice the swaddle-shush combo at the next fussy moment.",
    "2 min",
    "Karp H., The Happiest Baby on the Block (2002, 2015)"),
  w(6, "Watch Sleep Cues, Not the Clock",
    "Read the body, not your watch.",
    "Yawning, eye rubbing, ear pulling, glazed stare = the 5–10 minute window to sleep. Miss it and the second-wind cortisol surge can delay sleep 60–90 min.",
    ["Memorize the 4 main cues for your baby's age.", "Start wind-down at the first cue.", "Skip 'just one more book' if cues appear."],
    "She rubs her eyes during play → straight to bedtime, even if 10 min early.",
    "Pushing through cues to finish a chore — costs you the whole bedtime.",
    "Note her three most common tired signs.",
    "1 min",
    "Sadeh A., Sleep Med Rev (2007) 11(4):269–280"),
  w(7, "Add a Pre-Bed Topping-Off Feed",
    "Fuller stomach = longer first sleep stretch.",
    "A focused calorie-dense feed right before bed helps stretch the first sleep cycle. Cluster feeding 2–3 short feeds in the early evening boosts night-stretch length.",
    ["Offer a calm full feed 15 min before crib.", "For breastfed babies: cluster feed 5–7 PM.", "Keep the feed in dim light to preserve sleep cues."],
    "6:30 PM short feed, 7:00 PM full feed before crib at 7:30.",
    "Feeding to sleep — creates a feed-to-sleep association.",
    "Plan the bedtime feed at 15 min before lights-out tonight.",
    "20 min",
    "DeMarchis A. et al., Pediatrics (2015); WHO Infant Feeding Guidelines"),
  w(8, "Cut Stimulation 60 Min Before Bed",
    "Lower cortisol and arousal so melatonin can take over.",
    "Cortisol takes 30–60 min to drop after stimulation. Screens emit blue light that suppresses melatonin production by up to 50% (Chang et al., 2015).",
    ["No screens, tickles, or new toys 60 min before bed.", "Switch to dim warm-tone lights only.", "Speak in a quieter voice during wind-down."],
    "After 6:30 PM: warm lamp only, soft books, slow play.",
    "Showing 'just one cartoon' before bed — pushes sleep back 30+ min.",
    "Set a 60-min-before-bed phone reminder for 'wind-down mode'.",
    "Daily",
    "Chang A.M. et al., PNAS (2015) 112(4):1232–1237"),
  w(9, "Switch to a TOG-Rated Sleep Sack",
    "Safe warmth without the risk of loose blankets.",
    "AAP says no loose blankets, bumpers, or soft objects in the crib (2022). Sleep sacks rated by TOG (0.5–2.5) deliver consistent warmth, reducing arousals from cold.",
    ["Pick TOG by room temp (1.0 = 68–72 °F).", "Stop swaddling at first signs of rolling.", "Use a sack over a single-layer pajama."],
    "Room is 70 °F → cotton onesie + 1.0 TOG sleep sack.",
    "Adding extra blankets 'just in case' — overheating risk for SIDS.",
    "Buy or check TOG of current sleep sack today.",
    "5 min",
    "AAP Safe Sleep Recommendations (2022); SIDS Prevention Guidelines"),
  w(10, "Pick One Sleep-Training Method",
    "Consistency outperforms method choice every time.",
    "Cochrane reviews of behavioral sleep interventions (Ferber, chair, pickup-putdown, fading) show all reduce night waking when applied consistently for 7–14 nights.",
    ["Pick a method that fits your temperament.", "Commit to 14 nights without switching.", "Track wakings nightly to see the trend."],
    "Pick the chair method: sit by crib night 1, halfway out night 4, doorway night 7.",
    "Switching methods after 2 nights — resets the learning curve.",
    "Choose your method tonight and tell your partner.",
    "14 days",
    "Mindell J.A. et al., Sleep (2006) 29(10):1263–1276"),
  w(11, "Anchor a Consistent Wake-Up Time",
    "Set the circadian rhythm with the morning anchor.",
    "Light at the same time each morning sets the master clock (suprachiasmatic nucleus). Variable wake times scramble nap and bedtime cues.",
    ["Wake baby by the same time daily (within 30 min).", "Open curtains immediately for bright light.", "Resist letting her 'sleep in' after rough nights."],
    "Wake by 7:00 AM daily; nap 1 falls naturally at ~9:30.",
    "Letting baby sleep till 9 AM after a bad night — wrecks tonight's bedtime.",
    "Set an alarm for tomorrow's wake time.",
    "Daily",
    "Hanafin S., Roenneberg T., J Pineal Res (2007) 43(4):381–388"),
  w(12, "Track Sleep for 7 Days",
    "Patterns become obvious once you see them written down.",
    "Even 5 days of structured logging reveals the real pattern — usually a wake window or nap timing problem invisible without data.",
    ["Log wake/sleep times + naps for 7 days.", "Use the Huckleberry app or a paper grid.", "Look for the longest stretch — when did it happen?"],
    "By day 4 you spot 'every wake under 1 hr 45 follows a struggle bedtime'.",
    "Trying random changes without measuring — you can't see what's working.",
    "Start your sleep log right now with this morning's wake.",
    "1 week",
    "Sadeh A., Pediatrics (2004) 113(6):e570–e577"),
];

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 2 — EXCESSIVE CRYING
// ═══════════════════════════════════════════════════════════════════════════
const CRYING_WINS: InfantWin[] = [
  w(1, "Rule Out the Big Four First",
    "Solve the obvious cause before deeper troubleshooting.",
    "85% of infant crying resolves with a quick check of: hunger, dirty diaper, gas/burp, or tiredness. Quickly cycling through these saves enormous frustration.",
    ["Check diaper first.", "Offer feed (or burp if just fed).", "Calculate time since last sleep — is the wake window over?"],
    "She cried 30 min after a feed → tiredness was the answer, not hunger.",
    "Assuming hunger and over-feeding — leads to spit-up cycle.",
    "Make a 'big-4 checklist' card and stick on the fridge.",
    "2 min",
    "Brazelton T.B., Pediatrics (1962) 29:579–588"),
  w(2, "Apply the 5 S's Calming Reflex",
    "Trigger the built-in calming response under 4 months.",
    "Dr. Karp's 5 S's activate an automatic calming reflex in babies <4 mo. Studies show 90%+ stop crying within 60 seconds when all 5 are layered correctly.",
    ["Swaddle arms snug but legs loose.", "Hold on side/stomach in your arms (never sleep this way).", "Loud shush in ear + jiggle (small fast movements)."],
    "Swaddle → side hold → loud shush → 1 inch jiggle → silent in 45 sec.",
    "Gentle rocking — too slow to engage the reflex.",
    "Watch the 5 S's video and practice the swaddle once today.",
    "3 min",
    "Karp H., The Happiest Baby on the Block; Möller E.L. et al., Acta Paediatr (2019)"),
  w(3, "Try Skin-to-Skin Contact",
    "Use the most powerful regulator humans have.",
    "Skin-to-skin lowers infant cortisol, regulates heart rate, and triggers maternal oxytocin — proven in NICU and term infants alike (Moore et al., 2016).",
    ["Strip baby to diaper, you to chest bare.", "Cover both with a blanket.", "Hold for 20–30 min, breathing slowly."],
    "20 min skin-to-skin in a recliner during the witching hour calms both of you.",
    "Doing it stressed and rushed — your tension transfers via vagal tone.",
    "Try one 20-min skin-to-skin session today.",
    "20 min",
    "Moore E.R. et al., Cochrane Database Syst Rev (2016) 11:CD003519"),
  w(4, "Identify the Witching Hour",
    "Plan around the predictable evening crying window.",
    "Most babies have a fussy peak at 5–7 PM weeks 2–8 (Wessel's curve), peaking at week 6 and resolving by 12 weeks. Knowing it is coming changes everything.",
    ["Map your baby's worst 90-min window.", "Pre-plan: held, fed, dim, soothing.", "Hand off to partner if possible."],
    "5–7 PM = babywearing in the wrap with white noise on the porch.",
    "Trying to make dinner during witching hour — sets everyone up to fail.",
    "Block the witching hour on tomorrow's calendar.",
    "Daily",
    "Wessel M.A. et al., Pediatrics (1954); Barr R.G., Acta Paediatr Suppl (1990)"),
  w(5, "Burp Mid-Feed Every 2–3 Minutes",
    "Prevent the gas bubble that causes 30 min of post-feed crying.",
    "Babies <4 mo have an immature lower esophageal sphincter. Frequent small burps during feeding prevent the painful trapped-gas crying that follows.",
    ["Pause feed every 2–3 min for upright burp.", "Try the over-shoulder + sit-on-knee + face-down lap.", "Burp again at end before laying down."],
    "Switching breast → burp first → 70% fewer post-feed cries.",
    "Waiting till the end to burp — gas already painful by then.",
    "Set a 3-min burp reminder during the next feed.",
    "Per feed",
    "Vandenplas Y. et al., J Pediatr Gastroenterol Nutr (2015) 61(3)"),
  w(6, "Use Calm Voice + Slow Movement",
    "Mirror neurons in baby's brain copy your nervous system.",
    "Infants under 12 months read your tone, pace, and breath rate via mirror neurons. Your calm becomes their calm — but only if it's real, not performed.",
    ["Drop your voice an octave.", "Breathe out twice as long as in.", "Move at half your normal speed."],
    "Slow shushing in a low voice with hand on chest = quiet within 90 sec.",
    "High-pitched 'soothing' words — actually feels alarming to baby.",
    "Practice 1-min slow exhale before next pickup.",
    "1 min",
    "Iacoboni M., Annu Rev Psychol (2009) 60:653–670"),
  w(7, "Try a Babywearing Carrier",
    "Mimic the womb with motion + warmth + heartbeat.",
    "Hunziker & Barr (1986): carried infants cried 43% less. Use a hip-healthy carrier (M-position knees, neutral spine) like Ergobaby or a soft wrap.",
    ["Choose a TICKS-safe carrier (Tight, In view, Close to kiss).", "Wear baby high on chest, kissable.", "Walk for 20–30 min during fussy windows."],
    "Wrap on at 5:30 PM; cooked dinner without crying for 40 min.",
    "Bucket-style carriers — dangle baby's hips, can cause dysplasia.",
    "Practice putting on your carrier today.",
    "30 min",
    "Hunziker U.A., Barr R.G., Pediatrics (1986) 77(5):641–648"),
  w(8, "Recognize the PURPLE Crying Phase",
    "Normalize the peak crying period (2–8 weeks).",
    "PURPLE = Peak (week 6), Unexpected, Resists soothing, Pain-like face, Long lasting, Evening. The Period of PURPLE Crying program reframes 'colic' as normal development.",
    ["Read the PURPLE Crying parent guide (free online).", "Remember: nothing is wrong with your baby or your parenting.", "Plan safe step-aways when overwhelmed."],
    "Week 6 cried 4 hr/day; PURPLE chart said it would peak now and ease by week 12. It did.",
    "Believing 'I must be doing something wrong' — leads to harmful interventions.",
    "Bookmark dontshake.org PURPLE resources today.",
    "5 min",
    "Barr R.G., Period of PURPLE Crying Program (NCSBS, 2007)"),
  w(9, "Look for Reflux/Allergy Red Flags",
    "Spot the 5% of crying that has a medical cause.",
    "Most crying is normal, but persistent arching, projectile vomit, blood in stool, eczema, or poor weight gain warrant a pediatric evaluation for reflux (GERD) or CMPA.",
    ["Note: arching, choking, blood in stool, projectile vomit.", "Track symptom timing relative to feeds.", "Photograph eczema or rashes."],
    "Daily projectile vomit + arching → ped diagnosed reflux, treatment ended the daily 2-hr cry.",
    "Assuming all crying is normal — misses treatable conditions.",
    "Make a list of red flags before next ped visit.",
    "5 min",
    "AAP Clinical Report on GERD (2018); Vandenplas et al., JPGN (2015)"),
  w(10, "Build Your Crying Recovery Toolkit",
    "Plan your reset moves before you need them.",
    "Parental burnout is the #1 cause of dangerous interventions. Pre-planned 'reset' tools (a friend to call, a song, a tea ritual) prevent the spiral.",
    ["List 3 people you can call when crying overwhelms you.", "Identify 2 quick body resets (cold water, walk).", "Save a calming playlist on your phone."],
    "1 hr crying → text partner, splash cold water, deep breath × 5, return.",
    "Trying to 'just push through' — escalates burnout.",
    "Save 3 emergency contacts in your phone today.",
    "10 min setup",
    "Reijneveld S.A. et al., Lancet (2004) 364:1340–1342"),
  w(11, "Take Co-Regulation Breaks",
    "Put baby down safely when you are overwhelmed.",
    "When you reach the edge: place baby in the crib (safe), close the door, take a 5–10 min break. AAP and Period of PURPLE Crying both endorse this.",
    ["Place baby on her back in an empty crib.", "Set a 10-min timer.", "Breathe, splash water, text someone — return calm."],
    "Crying for 90 min, you're shaking → crib + 10 min break + return able to cope.",
    "Shaking baby — causes Shaken Baby Syndrome and is fatal.",
    "Memorize the 'crib + 10 min + breathe' rule.",
    "10 min",
    "AAP, Period of PURPLE Crying Program; CDC Abusive Head Trauma Prevention"),
  w(12, "Track Crying for 7 Days",
    "Make the invisible pattern visible.",
    "Logging crying timing, duration, and what worked surfaces patterns within 5–7 days. Often it's one specific wake window or feed timing.",
    ["Log start time, duration, what helped.", "Use the Huckleberry app or a notes file.", "Review on day 7 — circle the pattern."],
    "By day 5: every long cry happened after wake windows over 90 min.",
    "Random tries without tracking — can't tell what works.",
    "Start your crying log this evening.",
    "7 days",
    "Barr R.G., Pediatrics (1990); Kim P. et al., Behav Neurosci (2010)"),
];

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 3 — FEEDING ISSUES
// ═══════════════════════════════════════════════════════════════════════════
const FEEDING_WINS: InfantWin[] = [
  w(1, "Master Hunger Cues",
    "Feed before the cry — your output doubles.",
    "Early cues (rooting, hand-to-mouth, lip-smacking, stirring) precede crying by 10–20 min. Crying babies feed worse and tire faster, taking smaller volumes.",
    ["Watch for rooting, hand-to-mouth, lip-smacking.", "Offer feed at the first cue, not the last.", "Late cues = crying, head shaking, color change."],
    "She turned head + opened mouth → fed within 2 min, took full feed in 15.",
    "Waiting for crying — feed is harder, gassy, half-volume.",
    "Memorize the 3 early cues and check at every wake.",
    "1 min",
    "AAP Pediatric Nutrition Handbook (8th ed., 2019)"),
  w(2, "Check Latch & Bottle Flow Rate",
    "A wrong latch or nipple flow turns feeding into a fight.",
    "Shallow latch causes pain and poor transfer; bottle flow too fast causes choking and refusal. Most feeding 'issues' resolve with mechanical fixes.",
    ["Lips flanged, chin to breast, no clicking sound.", "Bottle: drip 1 drop/sec when inverted (slow flow).", "Try side-lying or laid-back nursing positions."],
    "Switched from medium to slow-flow nipple → refusal stopped overnight.",
    "Using fast-flow nipples 'so feeds are quicker' — causes oral aversion.",
    "Watch a latch video and re-check tonight's feed.",
    "5 min",
    "Wambach K., Riordan J., Breastfeeding and Human Lactation (5th ed.)"),
  w(3, "Feed in a Quiet Distraction-Free Zone",
    "Reduce competing stimuli for the easily distracted (3–6 mo).",
    "Around 3–4 months babies become socially aware and pull off the feed for any sound. Quiet, dim, low-stimulation feeds restore intake.",
    ["Move to a quiet dim room.", "No TV, phones, or other people present.", "Same chair, same blanket — sets the cue."],
    "Moved to bedroom for feeds at 4 mo → daily intake up 30%.",
    "Feeding in front of TV — guarantees pull-offs and gas.",
    "Pick your feeding spot now and clear it.",
    "5 min setup",
    "Field T., Infant Behav Dev (2007); LLLI Resources"),
  w(4, "Honor Baby-Led Pace",
    "Force-feeding teaches food refusal — pacing teaches trust.",
    "Responsive feeding (Pérez-Escamilla, 2017) is linked to better self-regulation, healthier weight trajectories, and lower obesity risk through age 6.",
    ["Stop when baby turns head, pushes bottle, or closes mouth.", "Never finish 'just one more oz'.", "Let baby set the duration."],
    "She pushed bottle at 4 oz → respected → next feed she took 6 oz happily.",
    "Saying 'finish your bottle' or shaking it in mouth — destroys appetite cues.",
    "Pause and wait next time she pulls off.",
    "Per feed",
    "Pérez-Escamilla R. et al., Adv Nutr (2017) 8(1):195S"),
  w(5, "Burp Strategically Mid + End",
    "Trapped gas mid-feed cuts intake by 30%.",
    "Babies swallow air; trapped gas creates fullness signals that stop the feed early. Mid-feed burping recovers that intake.",
    ["Burp at the midpoint of every feed.", "Burp again at the end before laying down.", "Try over-shoulder + sit-on-knee + face-down on lap."],
    "Mid-feed burp at 3 oz → baby resumed and took another 3 oz happily.",
    "Skipping burps to 'not interrupt' — interrupts more later with gas crying.",
    "Add a mid-feed burp pause to next feed.",
    "1 min",
    "Vandenplas Y. et al., J Pediatr Gastroenterol Nutr (2015)"),
  w(6, "Plan for Growth Spurts",
    "Sudden hunger jumps are biology, not regression.",
    "Predictable growth spurts at 7–10 days, 2–3 wk, 4–6 wk, 3 mo, 6 mo cause 24–48 hr of constant feeding. Knowing they exist prevents formula-supplementing panic.",
    ["Mark expected spurt windows on the calendar.", "Feed on demand for 24–48 hr — supply rebuilds.", "Don't supplement reactively unless ped advises."],
    "Day 12 = constant feeding 36 hr → by day 14 supply caught up, normal pattern resumed.",
    "Adding formula at the first spurt — undermines breastfeeding supply.",
    "Note next 3 spurt windows in your calendar.",
    "5 min",
    "Lawrence R.A., Lawrence R.M., Breastfeeding (8th ed., 2016)"),
  w(7, "Avoid Snacking — Plan Spaced Full Feeds",
    "Frequent small feeds = low intake + poor naps.",
    "Snack-feeding causes poor sleep (always slightly hungry) and poor feeds (never truly hungry). Full feeds every 2.5–3 hr work better for most >2 mo.",
    ["Aim for 2.5–3 hr between full feeds (>2 mo).", "If she fusses sooner, check sleep cues first.", "Make each feed a complete one (both breasts or full bottle)."],
    "Stretched from 90-min snacks to 2.5 hr full feeds → naps doubled.",
    "Offering breast for every fuss — creates feed-as-pacifier loop.",
    "Time today's feeds and check the spacing.",
    "Daily",
    "AAP Guidelines on Infant Feeding; Mohrbacher N., Breastfeeding Answers (2010)"),
  w(8, "Track Wet Diapers as Hydration Proxy",
    "Output tells you intake is adequate — better than weight checks.",
    "6+ wet diapers per 24 hr in a baby >1 wk old indicates adequate hydration and intake. This is the WHO-endorsed simple measure.",
    ["Count wet diapers daily for 3 days.", "Aim for 6+ heavy wet diapers in 24 hr.", "Note color — pale yellow = good."],
    "Counted 7 wet diapers/day → reassured intake was fine despite shorter feeds.",
    "Obsessing over feed times instead of measuring output.",
    "Start a 3-day diaper count today.",
    "Daily",
    "WHO/UNICEF Baby-Friendly Hospital Initiative (2018)"),
  w(9, "Try Different Feeding Positions",
    "A new position can fix a stalled latch or refused bottle.",
    "Side-lying, laid-back, football, and cross-cradle each engage different muscles and gravity. Bottle: paced upright, side-lying, or cradle-with-bottle-tilted.",
    ["Try a new position at the next feed.", "Watch baby's body — relaxed = working.", "Keep what works, drop what doesn't."],
    "Switched from cradle to side-lying for night feeds → both fell back asleep faster.",
    "Sticking to one position when it stops working.",
    "Try one new position today.",
    "Per feed",
    "Wambach K., Riordan J., Breastfeeding and Human Lactation (2020)"),
  w(10, "Identify the Distraction Phase (3–5 mo)",
    "Don't mistake a developmental phase for a feeding problem.",
    "At 3–5 mo babies pull off the feed every few seconds to look around. This is normal social development, not refusal. Adapt: shorter, quieter, more frequent feeds.",
    ["Move to a quiet dim room for feeds.", "Try wearing a feeding necklace (nursing necklace) for hands.", "Cluster shorter feeds when she's drowsy."],
    "4 mo daughter pulled off constantly in living room; bedroom feeds resumed normally.",
    "Worrying about supply when it's just curiosity.",
    "Plan tomorrow's feeds for the bedroom.",
    "Daily",
    "Mohrbacher N., Breastfeeding Answers Made Simple (2010)"),
  w(11, "Eliminate Common Allergens (CMPA Trial)",
    "Test for cow's milk protein allergy if symptoms align.",
    "CMPA affects 2–3% of babies. Symptoms: blood in stool, eczema, projectile vomit, fussy feeds. Mom's 2-week dairy elimination is the gold-standard trial.",
    ["Discuss with pediatrician first.", "Mom: cut all dairy + soy for 2 weeks.", "Track symptoms daily — improvement at 10–14 days = positive."],
    "Mom dropped dairy → blood in stool gone in 12 days, feeds smooth thereafter.",
    "Self-diagnosing without ped — may miss other causes.",
    "Book a ped visit if symptoms align with CMPA list.",
    "2 weeks",
    "Koletzko S. et al., J Pediatr Gastroenterol Nutr (2012) 55(2)"),
  w(12, "Consult on the Weight Curve",
    "Trust the trajectory, not single weigh-ins.",
    "Babies should track their own percentile curve, not move averages. Weighing at the same time, on the same scale, in nothing, gives a true picture.",
    ["Use the WHO growth chart for breastfed babies.", "Weigh once weekly max — daily weights mislead.", "Look at the trend over 3–4 weeks."],
    "Weight 'fell' at 3 weighs but trend matched her 25th percentile curve — no issue.",
    "Comparing your baby to another baby — different curves, different normals.",
    "Print or save WHO chart for your baby's sex.",
    "5 min",
    "WHO Child Growth Standards (2006); de Onis M., Acta Paediatr (2006)"),
];

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 4 — TEETHING DISCOMFORT
// ═══════════════════════════════════════════════════════════════════════════
const TEETHING_WINS: InfantWin[] = [
  w(1, "Distinguish Teething from Illness",
    "Teething doesn't cause high fever — don't miss the real illness.",
    "Wake et al. (2000) showed teething correlates only with mild gum pain, drooling, and chewing. Fever >38.4 °C, vomiting, or diarrhea = look elsewhere.",
    ["Check temp — over 38.4 °C is NOT teething.", "Note: drool, gum chewing, mild fuss = teething.", "Vomiting + rash = call pediatrician."],
    "39 °C fever blamed on teething → was actually an ear infection treatable with antibiotics.",
    "Blaming teething for illness symptoms — delays needed care.",
    "Save 38.4 °C as the 'check it' threshold.",
    "1 min",
    "Wake M. et al., Pediatrics (2000) 106(6):1374–1379"),
  w(2, "Use a Cold (Not Frozen) Teether",
    "Cold numbs gums; frozen damages tissue.",
    "Refrigerator-cold silicone or rubber teethers numb gums safely. Frozen plastic can crack and freeze-burn delicate gum tissue.",
    ["Refrigerate teethers (not freeze).", "Rotate 2–3 so one is always cool.", "Skip liquid-filled teethers (leak risk)."],
    "Three silicone teethers rotated through the fridge → constant relief during a molar week.",
    "Freezing teethers — too hard, can damage gums.",
    "Put 2 teethers in the fridge tonight.",
    "5 min",
    "AAP Guidance on Teething (2014); FDA Teether Safety Statement"),
  w(3, "Massage Gums with a Clean Finger",
    "Counter-pressure is what actually relieves pain.",
    "Gentle counter-pressure on the erupting gum desensitizes the area for several minutes — proven simple and effective in pediatric dental practice.",
    ["Wash hands well.", "Press finger gently along the gum line for 30 sec.", "Repeat 3–4 times during a fussy spell."],
    "Two minutes of finger massage gave her 20 min of calm play.",
    "Using teething gels with benzocaine — FDA warns of methemoglobinemia.",
    "Practice the gum massage at next pickup.",
    "2 min",
    "AAPD Guidelines on Infant Oral Health (2022)"),
  w(4, "Offer Cold Foods (after solids start)",
    "Edible cold = soothing + nutritious.",
    "After 6 mo, cold foods like chilled yogurt, breast milk popsicles in a mesh feeder, or refrigerated cucumber sticks numb gums while offering nutrition.",
    ["Try plain whole-milk yogurt cold.", "Freeze breast milk in mesh feeders.", "Offer cool cucumber sticks (over 6 mo, supervised)."],
    "Mesh feeder with frozen breast milk = 25 min of happy chewing.",
    "Honey or sweetened ice — honey banned <12 mo (botulism risk).",
    "Freeze 1 mesh-feeder breast milk pop tonight.",
    "10 min",
    "AAP Solid Food Introduction (2022); WHO Complementary Feeding"),
  w(5, "Skip Topical Numbing Gels",
    "Avoid the products that look like the answer.",
    "FDA (2018) issued a strong warning against benzocaine gels for under-2 due to methemoglobinemia risk. Belladonna and amber necklaces also lack safety evidence.",
    ["Read all teething product labels for benzocaine.", "Skip amber necklaces (strangulation + choke risk).", "Discuss any product with your pediatrician first."],
    "Threw out the benzocaine gel after FDA warning — switched to gum massage and cold.",
    "Trusting 'natural' homeopathic teething tablets — recalled for belladonna toxicity.",
    "Audit your teething products today.",
    "5 min",
    "FDA Drug Safety Communication (May 2018); CPSC Necklace Recall"),
  w(6, "Try a Mesh Feeder for Texture Therapy",
    "Combines cold + chewing + safe food exploration.",
    "Mesh or silicone feeders let baby chew solid food safely without choking risk. Cold + chewing is the most effective combination for teething pain.",
    ["Buy a silicone mesh feeder.", "Fill with frozen banana, mango, or breast milk.", "Always supervise during use."],
    "Frozen mango in mesh feeder = 30 min of independent happy gnawing.",
    "Leaving baby unsupervised with feeder — supervision still required.",
    "Buy or order a mesh feeder this week.",
    "10 min",
    "AAP Choking Prevention Guidelines (2020)"),
  w(7, "Manage Drool Rash with Barrier Cream",
    "Constant drool causes painful chin and chest rash.",
    "Saliva enzymes plus moisture cause irritant dermatitis. Petroleum jelly or zinc-oxide barrier creams prevent it; bibs absorb the moisture.",
    ["Apply a thin layer of petroleum jelly chin & neck before bed.", "Use absorbent bandana bibs daytime.", "Pat (don't rub) drool away."],
    "Vaseline at bedtime + bandana bibs by day = chin rash gone in 4 days.",
    "Wiping drool roughly — irritates skin further.",
    "Apply barrier cream at bedtime tonight.",
    "1 min",
    "American Academy of Dermatology, Pediatric Skin Care (2020)"),
  w(8, "Offer Extra Cuddles + Babywearing",
    "Physical comfort is the most underrated remedy.",
    "Skin-to-skin and being worn lower cortisol and provide constant soothing input. Often this alone removes the need for medications.",
    ["Wear baby in a carrier during fussy spells.", "Offer extra rocking or holding time.", "Co-bathe (skin-to-skin in water) for tough days."],
    "Worn for 2 hr in afternoon = fewer pain signals reached awareness.",
    "Trying to leave baby alone to 'self-soothe' through teething pain.",
    "Plan one extra babywearing session today.",
    "30 min",
    "Hunziker U.A., Barr R.G., Pediatrics (1986)"),
  w(9, "Use Pain Relief When Truly Needed",
    "Don't suffer when pediatrician-approved options exist.",
    "Acetaminophen (>2 mo) or ibuprofen (>6 mo) at correct weight-based dose can break a tough night. Always confirm dose with your pediatrician.",
    ["Confirm weight-based dose with ped.", "Use only at bedtime, not daily.", "Never combine with cold medications."],
    "One acetaminophen dose at bedtime turned a 4-wake night into 2 wakes.",
    "Daily pain meds — masks other issues, hard on liver.",
    "Save ped's correct dose chart on your phone.",
    "5 min",
    "AAP Section on Clinical Pharmacology (2020); FDA Pediatric Dosing Guide"),
  w(10, "Maintain Sleep Routine Through Teething",
    "Stick to the routine — teething is temporary.",
    "Teething peaks last 2–4 days. Letting the routine collapse creates new long-term sleep habits much harder to undo.",
    ["Keep bedtime routine identical.", "Add comfort within the routine, not new sleep crutches.", "Resume normal sleep training after the peak passes."],
    "Stuck to routine through 3 teeth coming in → no sleep regression after.",
    "Bringing baby to your bed for 'just teething nights' — becomes the new normal.",
    "Commit to your routine even on a teething night.",
    "Daily",
    "Mindell J.A. et al., Sleep Med Rev (2010) 14(2):89–96"),
  w(11, "Distract with Sensory Play",
    "Engagement reduces pain signal awareness.",
    "Pain neuroscience: focused attention reduces conscious pain perception. Engaging sensory play during fussy windows shortens crying spells.",
    ["Try water play in a small bin.", "Texture baskets (ribbons, cloth, brushes).", "Mirror play — babies love their reflection."],
    "10 min mirror play with rattles ended a 30-min teething cry.",
    "Pulling out screen 'distractions' — opposite of helpful.",
    "Set up a 5-min sensory tray today.",
    "10 min",
    "Wager T.D. et al., Science (2004) 303:1162–1167"),
  w(12, "Track Tooth Eruption Order",
    "Knowing what's coming reduces fear of the unknown.",
    "Teeth emerge in a predictable order (lower central incisors first ~6 mo, molars worst at 13–19 mo). The chart turns mystery into a forecast.",
    ["Note each tooth as it appears.", "Use the AAPD eruption chart to predict the next one.", "Watch for molars (13–19 mo) — usually the worst.",],
    "Knowing molars cause 4 fussy days helped us pre-plan calm activities.",
    "Assuming every fussy week is a tooth — sometimes other things.",
    "Print the AAPD eruption chart today.",
    "5 min",
    "American Academy of Pediatric Dentistry, Eruption Chart (2022)"),
];

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 5 — NOT EATING SOLIDS
// ═══════════════════════════════════════════════════════════════════════════
const SOLIDS_WINS: InfantWin[] = [
  w(1, "Confirm Readiness Signs",
    "Don't start solids before the body is ready.",
    "AAP readiness signs (around 6 mo): sits with minimal support, tongue thrust reflex gone, watches you eat with interest, doubled birth weight.",
    ["Check: sits, no tongue-thrust, interest, head control.", "Wait if any sign is missing.", "Talk to ped if uncertain."],
    "5.5-mo daughter pushed food out → waited 2 weeks → readiness arrived and feeds went well.",
    "Starting at 4 mo because cousin did — risks aspiration and allergy issues.",
    "Tick the 4 readiness signs today.",
    "5 min",
    "AAP Section on Breastfeeding (2022); WHO Complementary Feeding"),
  w(2, "Start with Iron-Rich Single Foods",
    "Iron stores from birth deplete by 6 mo — solids must rebuild them.",
    "WHO and AAP both recommend iron-rich first foods (meat purée, iron-fortified cereal, lentils) over fruits or rice cereal.",
    ["First food: meat purée, lentils, or iron-fortified oats.", "One single ingredient at a time, 3 days apart.", "Watch for any reaction (rash, vomit, stool change)."],
    "Started with chicken purée at 6 mo → iron levels stayed normal at 9-mo check.",
    "Starting with rice cereal — low iron, low nutrition density.",
    "Plan tomorrow's first food and prep it tonight.",
    "10 min",
    "AAP Pediatric Nutrition Handbook (8th ed.); WHO IYCF Guidelines"),
  w(3, "Offer Same Food 8–15 Times",
    "Acceptance is built through repetition, not a single try.",
    "Maier et al. (2007) showed infants accept new tastes after 8–10 exposures, often after initial rejection. Most parents quit at 2–3 tries.",
    ["Re-offer rejected foods every other day.", "Don't change preparation each time — keep it consistent.", "Track exposures in a notes file."],
    "Broccoli rejected 6 times → accepted on try 9 → became a favorite by month-end.",
    "Quitting after 2 tries and labeling baby a 'picky eater'.",
    "Pick one rejected food to re-try this week.",
    "Per meal",
    "Maier A. et al., Clin Nutr (2007) 26(6):788–797"),
  w(4, "Try Baby-Led Weaning Strips",
    "Self-feeding builds independence and oral skills.",
    "Brown & Lee (2015): BLW babies show better self-regulation and lower obesity risk at 18 mo. Foods cut as long thick strips (steamed carrot, banana) are safe by 6 mo.",
    ["Cut food into adult-finger-sized strips.", "Steam soft enough to squish between fingers.", "Sit baby upright in chair, supervise constantly."],
    "Steamed sweet potato sticks → daughter fed herself happily for 30 min.",
    "Round, hard, or coin-shaped foods — choking risk (grapes, hot dogs, popcorn).",
    "Steam 3 BLW strips for tomorrow's lunch.",
    "15 min",
    "Brown A., Lee M., JAMA Pediatr (2015); BLW Safe Cutting Guide"),
  w(5, "Eat Together (Modeling)",
    "Babies learn what to eat by watching you.",
    "Mirror neuron + social learning research: infants are 3× more likely to try a new food when a trusted adult eats it first in front of them.",
    ["Sit at the table together at least once a day.", "Eat the same food (with seasoning if desired for you).", "Show enjoyment visibly — facial expressions matter."],
    "Ate broccoli with delight in front of her → she reached for hers within 2 min.",
    "Feeding baby separately — misses the most powerful learning channel.",
    "Plan one shared meal for tomorrow.",
    "30 min",
    "Mennella J.A., Beauchamp G.K., Pediatrics (2010) 125(4):e791"),
  w(6, "Vary Texture Gradually",
    "Texture exposure 6–10 mo prevents picky eating later.",
    "Coulthard et al. (2009): babies introduced to lumps after 9 mo had significantly more feeding problems and pickier eating at age 7.",
    ["Move from purée → lumpy → mashed → soft chunks by 9 mo.", "Mix textures within a meal.", "Offer finger foods alongside spoon-fed."],
    "By 8 mo, mashed avocado with soft toast → easy progression to family food.",
    "Sticking to smooth purée past 9 mo — sets up later texture aversion.",
    "Add one new texture this week.",
    "Daily",
    "Coulthard H. et al., Matern Child Nutr (2009) 5(1):75–85"),
  w(7, "Skip Salt, Sugar, Honey (Under 1)",
    "Three rules that protect kidneys, taste buds, and life.",
    "Honey carries botulism risk before 12 mo. Salt strains immature kidneys. Added sugar shapes lifelong taste preferences toward sweet.",
    ["No added salt to baby's food (her food, not yours).", "No honey under 12 mo, ever.", "Skip added sugar — let real fruit be sweet."],
    "Cooked plain version of family meal for baby; no salt added until age 1.",
    "Sharing 'just a taste' of honey or sweet drinks before 1.",
    "Audit your baby's pantry today.",
    "10 min",
    "AAP Statement on Honey & Botulism; WHO Sugar Guidelines (2015)"),
  w(8, "Use a Divided High-Chair Plate",
    "Visual organization increases acceptance.",
    "Suction-base divided plates let baby explore foods separately. Small portions feel manageable and reduce overwhelm.",
    ["Use a 3-section suction silicone plate.", "Offer 1 tbsp of each food.", "Include 1 known + 1 new food + 1 fun-texture food."],
    "Plate of yogurt + new beet + favorite cracker → ate all three.",
    "Piling food in one big mound — visually overwhelming for baby.",
    "Buy or use your divided plate at next meal.",
    "5 min",
    "Daniels L.A. et al., Int J Behav Nutr Phys Act (2014) 11:27"),
  w(9, "Make Mealtime a 20-Min Window",
    "Long meals teach distraction; short meals teach focus.",
    "Mealtimes longer than 30 min reduce engagement and cause grazing patterns. The ideal: 15–20 min with a clear start and end.",
    ["Set a soft timer for 20 min.", "End meal when she stops eating, not when plate is empty.", "No grazing between meals."],
    "Cut meals from 45 to 20 min → intake actually went up next day.",
    "Chasing baby with spoon for 45 min — teaches eating is a battle.",
    "Set a 20-min timer at next meal.",
    "Per meal",
    "Satter E., Child of Mine: Feeding with Love and Good Sense (2000)"),
  w(10, "Include Allergens Early",
    "Early introduction of peanut, egg, dairy reduces allergy risk by 80%.",
    "LEAP study (2015): early peanut introduction reduced allergy by 81%. EAT study (2016) extended this to multiple allergens at 4–6 mo.",
    ["Introduce peanut (smooth peanut butter thinned), egg, dairy, fish around 6 mo.", "One allergen at a time, 3 days apart.", "Watch for hives, vomit, breathing change."],
    "Smooth peanut butter on toast at 7 mo → 2 yr later no peanut allergy.",
    "Delaying allergens till 1+ — increases (not decreases) allergy risk.",
    "Plan first peanut intro this week.",
    "10 min",
    "Du Toit G. et al., NEJM (2015) 372:803–813 (LEAP study)"),
  w(11, "Don't Replace Refused Meals with Bottle",
    "Bottle backups teach baby to skip solids.",
    "If solids are refused and milk is offered as backup, baby learns the milk path is easier. Skip the meal, offer same food next time.",
    ["If she refuses solids, offer water in cup.", "Don't add bottle — wait till next scheduled feed.", "Re-offer the same food at next meal."],
    "Refused dinner → no bottle → ate it eagerly at breakfast.",
    "Bottle-bribing eaten food — never builds appetite for solids.",
    "Decide your no-bottle-backup rule today.",
    "Per meal",
    "Satter E., Family Nutrition Series (2008); ESPGHAN Solid Food Guidelines"),
  w(12, "Track Tolerance & Reactions",
    "Build a 30-day exposure log to spot patterns.",
    "Logging foods + reactions surfaces real allergies vs phases. Most 'reactions' are texture or temperature aversions — patterns reveal it.",
    ["Note: food, date, reaction (none/mild/severe).", "Photo any rash for the ped.", "Review weekly — circle real patterns."],
    "Log showed daily 'rash' was only after tomato — confirmed mild contact reaction.",
    "Avoiding everything she once spit out — eliminates whole food groups.",
    "Start a food log on a notes app today.",
    "30 days",
    "AAP Allergy Statement (2019); EAACI Food Allergy Guidelines"),
];

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 6 — FREQUENT NIGHT WAKING
// ═══════════════════════════════════════════════════════════════════════════
const NIGHT_WAKING_WINS: InfantWin[] = [
  w(1, "Distinguish Hunger vs Habit Wake",
    "Stop feeding what is no longer hunger.",
    "After 6 mo most babies don't need night calories. Wakes after that are usually habit, sleep-cycle confusion, or sleep-association issues.",
    ["Note time and behavior of each wake.", "Wakes <2 hr after a feed = rarely hunger.", "Test: offer water — refusal = it was habit."],
    "11 PM 'feed' wake → baby took 1 oz then back to sleep → it was habit.",
    "Feeding every wake reflexively — reinforces the wake pattern.",
    "Track tonight's wakes with the test above.",
    "1 night",
    "Mindell J.A. et al., Sleep (2010) 33(5):683–688"),
  w(2, "Drop Calorie Wake-Ups Gradually (8 mo+)",
    "Decrease feed length by 1 minute per night.",
    "Pediatric Sleep Council recommends gradual feed reduction over 2 weeks, allowing supply and baby's appetite to shift to daytime.",
    ["Cut 1 min off each night feed every 2 nights.", "Or reduce bottle by 1 oz every 2 nights.", "Increase daytime feed volume by same amount."],
    "Started at 8 oz at 8 mo → down to 0 oz over 16 nights → uninterrupted sleep.",
    "Cold-turkey dropping a feed — supply issues + crying spike.",
    "Tonight: cut 1 min off the longest feed.",
    "2 weeks",
    "Pediatric Sleep Council Guidelines; Mindell J.A. (2009)"),
  w(3, "Use the Pause Method",
    "Wait 60 seconds before responding — most wakes self-resolve.",
    "Babies have brief 'partial arousals' between sleep cycles. Rushing in interrupts the natural transition back to sleep.",
    ["Pause 60 sec before responding to any cry.", "Time it on your phone — 60 sec feels long.", "Only intervene if cry escalates or signals real need."],
    "Cry started → waited 60 sec → she resettled in 45 sec.",
    "Rushing in at the first whimper — wakes her fully.",
    "Practice the 60-sec pause once tonight.",
    "1 night",
    "Burnham M.M. et al., J Child Psychol Psychiatry (2002)"),
  w(4, "Keep Night-Times Boring",
    "Make awake-at-night the most boring choice in baby's life.",
    "Light, talk, and play at night reinforce wake. Pitch dark, silent, all-business is the proven approach.",
    ["Use a dim red night-light only (red doesn't suppress melatonin).", "No talking beyond a soft 'shh'.", "Diaper change only if soiled."],
    "Switched from white to red night-light → wake-up stretches doubled.",
    "Phone screens during night feeds — destroys both your and baby's melatonin.",
    "Buy or set a red night-light tonight.",
    "10 min",
    "Wright H.R., Lack L.C., Chronobiol Int (2001) 18(5):801–808"),
  w(5, "Address the Sleep Crutch",
    "Whatever puts baby to sleep at bedtime, she'll need at every wake.",
    "Sleep onset associations (rocking, nursing, holding) are recreated at every sleep-cycle transition. Breaking them is the single biggest fix.",
    ["Identify the bedtime crutch (rock, feed, hold).", "Move it earlier in the routine, separate from sleep.", "Place baby down drowsy-but-awake."],
    "Stopped feeding-to-sleep → 4-wake nights became 1-wake within 5 days.",
    "Replacing one crutch with another — same problem, different shape.",
    "Identify your current sleep crutch tonight.",
    "1 week",
    "Sadeh A., Sleep Med Rev (2010); Mindell J.A. (2006)"),
  w(6, "Manage Sleep Regressions",
    "Predictable regressions at 4, 8, 12, 18 mo are not your fault.",
    "Regressions coincide with brain leaps and motor milestones. They last 2–6 weeks; consistency is the only fix.",
    ["Mark regression windows on your calendar.", "Hold the routine — don't introduce new crutches.", "Add daytime motor practice for the relevant milestone."],
    "8-mo regression → held the routine → resolved in 18 days, no new habits.",
    "Bringing baby to bed 'just for the regression' — usually permanent.",
    "Note your next expected regression window.",
    "Per regression",
    "Galland B.C. et al., Sleep Med Rev (2012); Plooij F. (2014)"),
  w(7, "Optimize Daytime Naps",
    "An overtired baby wakes more, not less.",
    "Sleep begets sleep — Weissbluth's principle. Skipping naps does not 'tire baby out'; it floods the system with cortisol.",
    ["Prioritize the morning nap (most restorative).", "Match nap counts to age (3 → 2 → 1 by 18 mo).", "Cap last nap to end 4 hr before bedtime."],
    "Saved morning nap → night wakes dropped from 4 to 1.",
    "Skipping naps to 'help sleep' — backfires every time.",
    "Plan tomorrow's naps now.",
    "Daily",
    "Weissbluth M. (2015); Acebo C. et al., Sleep (2005)"),
  w(8, "Try an Earlier Bedtime",
    "Counter-intuitive: an earlier bedtime reduces night wakes.",
    "Crampton et al. (2009): earlier bedtimes (before 8 PM) result in longer total night sleep and fewer wakings, even when wake time stays the same.",
    ["Move bedtime 15 min earlier each night.", "Aim for 7:00–7:30 PM for under-2.", "Watch for tired cues earlier than expected."],
    "Bedtime moved from 8:30 to 7:00 → night wakes dropped from 5 to 2.",
    "Pushing bedtime late hoping she'll sleep in — backfires.",
    "Tonight: bedtime 15 min earlier than usual.",
    "Daily",
    "Crampton J. et al., Sleep (2009); Mindell J.A. (2009)"),
  w(9, "Check Room Temp & Sleepwear Fit",
    "Wakes from cold or overheating are silent — fix the environment.",
    "AAP guidance: 68–72 °F (20–22 °C). Overheating is linked to SIDS risk and frequent wakes. Sleep sack TOG should match the room.",
    ["Use a room thermometer.", "Pick TOG based on temp (1.0 for 68–72 °F).", "Check baby's chest (not hands) for warmth."],
    "Room was 76 °F → cooled to 70 °F → wakes dropped immediately.",
    "Adding extra blankets in winter — causes overheat wakes.",
    "Buy or check your room thermometer today.",
    "5 min",
    "AAP Safe Sleep Guidelines (2022)"),
  w(10, "Use Wake-to-Sleep for Same-Time Wakes",
    "Resets the sleep cycle when baby wakes at the exact same time nightly.",
    "Pantley's wake-to-sleep technique: gently rouse baby 30 min before her habitual wake time. This shifts her sleep cycle and breaks the pattern.",
    ["Note the exact wake time for 3 nights.", "Set alarm for 30 min before that time.", "Briefly rouse baby (don't fully wake), then leave."],
    "Wake-to-sleep at 1:00 AM (before her 1:30 wake) → 1:30 wake gone in 4 nights.",
    "Trying for random wakes — only works for habitual same-time wakes.",
    "Identify if your baby has a habitual wake time.",
    "1 week",
    "Pantley E., The No-Cry Sleep Solution (2002)"),
  w(11, "Build Self-Soothing Skills Gradually",
    "Self-soothing is a skill that takes practice — start small.",
    "Building bridges (lovey, thumb, paci self-replacement after 12 mo) gives baby self-regulation tools so she doesn't need you between cycles.",
    ["Introduce a safe lovey (after 12 mo per AAP).", "Teach paci self-replacement with multiple in the crib.", "Practice 'down awake' for one nap a day."],
    "Multiple pacifiers in the crib at 9 mo → she found one herself, no more wakes.",
    "Skipping the building-blocks and expecting overnight success.",
    "Choose one self-soothing tool to introduce.",
    "1 month",
    "AAP Pacifier and Lovey Guidelines (2022)"),
  w(12, "Log Wakings to Find the Pattern",
    "5–7 days of data ends the guesswork.",
    "Patterns appear in days, not weeks. Most night-waking issues resolve once the trigger window is identified.",
    ["Log: time of wake, behavior, what helped.", "Use Huckleberry app or notes file.", "Day 7: circle the pattern."],
    "Log showed every wake was 22 min after a daytime nap that ran past 4 PM.",
    "Random changes without measuring — can't isolate cause.",
    "Start tonight's wake log.",
    "1 week",
    "Sadeh A., Pediatrics (2004) 113(6):e570"),
];

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 7 — ALWAYS IRRITABLE
// ═══════════════════════════════════════════════════════════════════════════
const IRRITABLE_WINS: InfantWin[] = [
  w(1, "Audit Your Sensory Input",
    "Most chronic irritability is silent overstimulation.",
    "Babies process 1/5 the sensory input adults can handle. TV noise, lights, multiple talkers, scrolling phones flood their nervous system.",
    ["List 5 sensory inputs in your home (TV, music, lights).", "Cut at least 2 — usually background TV.", "Watch baby's mood for 3 days."],
    "Killed background TV → baby's afternoon mood transformed in 4 days.",
    "Assuming irritability is about her — when it's about her environment.",
    "Turn off background TV right now.",
    "5 min",
    "Christakis D.A. et al., Pediatrics (2009) 124(3):971–977"),
  w(2, "Lower the Activity Bar",
    "Less stimulation, not more, fixes most fussy babies.",
    "Modern parents over-program babies. Free unstructured floor time + outdoor time outperforms classes for under-2s in every developmental measure.",
    ["Drop one scheduled activity this week.", "Replace with 30 min floor play at home.", "Plan for one calm 'do nothing' hour daily."],
    "Cancelled music class → afternoon meltdowns ended.",
    "Filling every hour 'so she doesn't get bored' — she's overwhelmed.",
    "Pick one activity to remove from this week.",
    "Weekly",
    "AAP Family Media Plan; Brazelton T.B., Touchpoints (2006)"),
  w(3, "Build Boring Time Into the Day",
    "Boredom is where regulation builds.",
    "Brain research (Immordino-Yang, 2012): unstimulated downtime is essential for emotional integration and self-regulation development.",
    ["Schedule 30 min of 'nothing' daily.", "No screens, no music, no talking.", "Let baby explore one safe area at her own pace."],
    "Floor time alone with two wooden spoons = 35 min of focused calm play.",
    "Filling silence with songs/talking — denies the regulation window.",
    "Block 30 min of boring time tomorrow.",
    "Daily",
    "Immordino-Yang M.H. et al., Perspect Psychol Sci (2012) 7(4):352"),
  w(4, "Check for Hidden Hunger or Tiredness",
    "Two-thirds of irritability traces to one of these.",
    "Babies under 2 cannot self-monitor needs. The first solution is usually the simplest: feed or sleep.",
    ["Time since last feed?", "Time since last sleep?", "Address the bigger gap first."],
    "Crankiness at 4 PM → feed missed since lunch → fed → calm in 10 min.",
    "Trying complex solutions when basic needs unmet.",
    "Quick check both at next fussy moment.",
    "1 min",
    "Brazelton T.B., Touchpoints (2006); AAP Anticipatory Guidance"),
  w(5, "Identify Sensory Profile",
    "Sensory-sensitive vs sensory-seeking babies need opposite approaches.",
    "Dunn's Sensory Profile (1997): sensitive babies need less input, seekers need more deep pressure/movement. Mixing them up makes things worse.",
    ["Notice: does she calm with movement (seeker) or stillness (sensitive)?", "Does she startle at sounds or not (sensitive vs low-registration)?", "Adjust day's pace to match."],
    "Realized she was sensory-seeking → added swing time → afternoon calm.",
    "Forcing a quiet day on a seeker — she escalates trying to get input.",
    "Observe baby's profile this week.",
    "1 week",
    "Dunn W., Infants & Young Children (1997) 9(4):23–35"),
  w(6, "Use Predictable Transitions",
    "Surprise transitions trigger meltdowns.",
    "Babies and toddlers thrive on prediction. A 2-min verbal warning + visual cue cuts transition meltdowns by ~70% (Greenfield & Lin, 2015).",
    ["Give 'in 2 min we leave' warnings.", "Use a song or visual cue for each transition.", "Same routine for the same transition daily."],
    "'In 2 min, bath time' + bath song → no more bath protest.",
    "Pulling baby from one activity straight into another — guarantees protest.",
    "Add one transition warning today.",
    "Daily",
    "Greenfield E.A., Lin M.E., Child Dev (2015)"),
  w(7, "Add a Daily Outdoor Walk",
    "Sunlight + nature = nature's mood reset.",
    "Outdoor exposure regulates circadian rhythm, increases vitamin D, and exposes baby to slow visual + auditory input — all proven mood regulators.",
    ["Aim for 30 min outdoors daily, ideally morning.", "Walk in stroller, carrier, or just sitting in the grass.", "Skip screens during the walk."],
    "Daily 9 AM walk = better naps + better mood by lunch.",
    "Skipping outdoors in 'busy weeks' — irritability spikes within days.",
    "Schedule tomorrow's walk now.",
    "Daily",
    "Tillmann S. et al., J Epidemiol Community Health (2018)"),
  w(8, "Practice Co-Regulation Breathing",
    "Your slow breath becomes baby's nervous system.",
    "Polyvagal theory (Porges): infant ANS borrows regulation from primary caregiver. Slow exhales trigger vagus nerve calming in baby via mirror.",
    ["Hold baby chest-to-chest.", "Breathe out longer than in (4 in, 8 out).", "Hum a low note on the exhale."],
    "3 minutes of slow humming exhales calmed a 30-min meltdown.",
    "Trying to calm baby while you're escalated — your tone transfers.",
    "Practice 1 min of slow exhales right now.",
    "3 min",
    "Porges S.W., Polyvagal Theory (2011)"),
  w(9, "Reduce Screen Exposure",
    "AAP: zero screens under 18 months (except video calls).",
    "Christakis (2009) showed even background TV reduces parent-infant talk by 12% per hour, leading to language delays and increased irritability.",
    ["Audit your screens — TV, phones, tablets.", "Designate screen-free zones (kitchen, dining, bedroom).", "Replace screen time with floor play."],
    "Removed screens before naps → naps lengthened from 30 to 90 min.",
    "Phone scrolling while feeding — baby reads disconnection.",
    "Designate one screen-free hour today.",
    "Daily",
    "AAP Media Use Guidelines (2016, 2022)"),
  w(10, "Rule Out Discomfort",
    "Chronic low-grade discomfort makes any baby irritable.",
    "Reflux, constipation, ear infection, eczema, food sensitivity — all cause persistent fussiness without obvious symptoms.",
    ["Check: stool pattern, ear pulling, skin, breathing.", "Note timing — after feeds suggests reflux.", "Photograph rashes for ped."],
    "Ear-pulling for 3 days = ear infection diagnosed → 24 hr after antibiotic, mood transformed.",
    "Assuming irritability is 'just personality' — misses treatable cause.",
    "Schedule a ped check if irritability is constant.",
    "30 min visit",
    "AAP Anticipatory Guidance; AAP Statement on Otitis Media (2013)"),
  w(11, "Build a Calm-Down Sensory Kit",
    "Pre-curated tools beat panic-Googling at meltdown moment.",
    "Having 5 reliable tools ready cuts meltdown duration in half (occupational therapy practice).",
    ["Assemble 5 tools: lovey, music, water bottle, low light, heavy blanket.", "Keep kit accessible (not in storage).", "Use the same kit every meltdown."],
    "Kit on the shelf → meltdown → kit out → calm in 6 min vs 30.",
    "Trying random new strategies in crisis moment.",
    "Assemble your kit today.",
    "20 min",
    "Greenspan S.I., The Child with Special Needs (1998)"),
  w(12, "Track Triggers for 7 Days",
    "Patterns surface within a week.",
    "Triggers are usually one of 6: hunger, sleep, sensory overload, hidden discomfort, transition surprise, or screen time.",
    ["Log: time, mood, last sleep, last feed, recent input.", "Use Huckleberry or notes file.", "Day 7: circle the recurring trigger."],
    "Log showed every meltdown was within 1 hr of a missed nap window.",
    "Trying to fix without seeing the pattern.",
    "Start the trigger log this evening.",
    "1 week",
    "Sadeh A., Pediatrics (2004); AAP Bright Futures Guidelines"),
];

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 8 — NOT REACHING MILESTONES
// ═══════════════════════════════════════════════════════════════════════════
const MILESTONE_WINS: InfantWin[] = [
  w(1, "Know the Range, Not the Average",
    "Milestones are normal across a wide window.",
    "WHO data: walking is normal anywhere from 8.5 to 17.6 months. Comparing to one number causes unnecessary panic.",
    ["Look up the WHO/CDC range for each milestone.", "Note baby's percentile for context.", "Watch for steady forward progress, not date."],
    "13-mo not walking — within WHO range — actually walked at 14 mo.",
    "Comparing to one cousin or social media baby.",
    "Save WHO milestone range chart on phone.",
    "5 min",
    "WHO Multicentre Growth Reference Study (2006)"),
  w(2, "Maximize Tummy Time",
    "Floor strength is the foundation for every motor milestone.",
    "AAP recommends 1 hour of tummy time by 3 months in 3 sessions. It strengthens the chain that enables rolling, sitting, crawling, and walking.",
    ["3 short sessions daily, increase to 1 hr by 3 mo.", "Get on the floor with her — face her.", "Use a mirror or book at her eye level."],
    "Built tummy time to 60 min/day → rolled at 4.5 mo right on schedule.",
    "Skipping tummy time because baby cries — extends crying overall.",
    "Do one 5-min tummy time session today.",
    "Daily",
    "AAP Tummy Time Guidelines (2022); Hewitt L. et al., Pediatrics (2017)"),
  w(3, "Encourage Floor Play (over containers)",
    "Containers (bouncers, walkers, jumpers) limit motor development.",
    "Garrett et al. (2002): excessive container use delayed motor milestones by 1–2 months. Floor play allows full body movement.",
    ["Limit containers to 15 min total per day.", "Replace with safe floor mat time.", "Eliminate baby walkers (Health Canada banned them)."],
    "Cut walker time → cruising started 3 weeks earlier.",
    "Using bouncers/jumpers as default activity — restricts motor exploration.",
    "Set up a safe floor area today.",
    "Daily",
    "Garrett M. et al., BMJ (2002); AAP Walker Statement"),
  w(4, "Talk Constantly (Parentese)",
    "Babies who hear 21,000+ words/day develop language fastest.",
    "Hart & Risley (1995): the 30-million-word gap. Parentese (slow, melodic, exaggerated) is processed 5× more by infant brain than adult speech.",
    ["Narrate everything you do.", "Use parentese tone (high pitch, slow).", "Pause and wait for baby's response."],
    "Narrated grocery shopping → 5 new words by 13 mo.",
    "Silent caregiving — misses the entire language input window.",
    "Narrate next 5 actions you do today.",
    "Daily",
    "Hart B., Risley T.R. (1995); Ramirez-Esparza N. et al. (2014)"),
  w(5, "Read Aloud Daily",
    "Even infants benefit from daily reading.",
    "AAP Bright Futures: daily reading from birth boosts language, attention, and bonding. The voice and rhythm matter as much as the words.",
    ["Read 1 board book daily, any age.", "Let baby chew/turn pages.", "Use voices, sound effects."],
    "Daily reading from 4 mo → first 'word' (book name) at 11 mo.",
    "'Too young to understand' — they understand the bond and rhythm.",
    "Read one board book today.",
    "5 min",
    "AAP Council on Early Childhood, Pediatrics (2014)"),
  w(6, "Limit Screen Time (AAP Guidance)",
    "Zero screens under 18 mo (except video calls with family).",
    "Christakis (2009): each hour of TV displaces 770 adult words. Verbal interaction directly correlates with milestone achievement.",
    ["Audit current screen exposure.", "Replace with face-to-face interaction.", "Video calls with family are okay."],
    "Cut all screens → vocabulary doubled in 2 months.",
    "'Just one show' — sets up screen as default.",
    "Track today's screen exposure honestly.",
    "Daily",
    "AAP Media and Young Minds (2016, 2022)"),
  w(7, "Use the CDC Milestone Tracker App",
    "Free, accurate, and updated for the 2022 milestone changes.",
    "CDC's free 'Milestone Tracker' app uses revised 2022 evidence-based milestones (75% of children should achieve, not 50%).",
    ["Download CDC Milestone Tracker app.", "Complete monthly checklist.", "Share results with pediatrician."],
    "App flagged a 9-mo communication concern → early intervention started early → resolved.",
    "Self-comparing to old milestone lists — outdated.",
    "Download the app today.",
    "10 min",
    "CDC Learn the Signs Act Early Program (2022 update)"),
  w(8, "Target Each Domain",
    "Don't focus only on motor — language, social, cognitive matter equally.",
    "Holistic development needs all four domains: gross motor, fine motor, language/social, cognitive. Strength in one masks gaps in another.",
    ["Pick one daily activity per domain.", "Motor: tummy time/cruising. Language: read/sing.", "Social: peek-a-boo. Cognitive: shape sorters."],
    "Daily 4-domain plan → rounded development at 12-mo check.",
    "Only working on what comes naturally to your baby.",
    "Plan one activity per domain for tomorrow.",
    "Daily",
    "Brazelton T.B., Touchpoints (2006); CDC Domain Framework"),
  w(9, "Schedule the 9, 18, 24 Wellness Visits",
    "These are the AAP-mandated developmental screening points.",
    "AAP requires structured developmental screening (M-CHAT, ASQ-3) at 9, 18, and 24 months. These catch 80% of developmental concerns early.",
    ["Confirm 9-mo, 18-mo, 24-mo visits booked.", "Bring filled-out CDC checklist to each.", "Ask specifically about M-CHAT (autism screen) at 18 + 24 mo."],
    "M-CHAT at 18 mo flagged concern → ASD diagnosed at 22 mo → early intervention from 23 mo.",
    "Skipping the 'fine' check-ups — misses the screening windows.",
    "Confirm next wellness visit is on calendar.",
    "5 min",
    "AAP Bright Futures Periodicity Schedule (2023)"),
  w(10, "Request Free Early Intervention Eval",
    "If concerned, an evaluation is free and your right.",
    "IDEA Part C (US) and most countries provide free developmental evaluations for under-3s. No referral needed; parents can self-refer.",
    ["Search 'Early Intervention + your state'.", "Self-refer — no doctor needed.", "Eval is free; services are free or low-cost."],
    "Self-referred at 14 mo concern → speech therapy started at 15 mo → talking by 22 mo.",
    "Waiting and hoping — early intervention is most effective before age 3.",
    "Look up your local Early Intervention number.",
    "30 min",
    "IDEA Part C; Hebbeler K. et al., Pediatrics (2007)"),
  w(11, "Build Routines that Embed Skills",
    "Daily routines are the most powerful learning environment.",
    "Embedded learning during routines (bath, dressing, feeding) leverages repetition + warmth — the two most powerful teaching factors.",
    ["Name body parts during dressing.", "Count steps when going up.", "Sing the same song during bath."],
    "Daily 'wash the toes' → she pointed to toes when asked at 11 mo.",
    "Treating routines as chores instead of teaching opportunities.",
    "Pick one routine to embed a skill in tomorrow.",
    "Daily",
    "Bronfenbrenner U., Ecological Systems Theory; Vygotsky"),
  w(12, "Document with Video",
    "Video clips are the best record for pediatricians.",
    "Short videos of milestones (or concerns) give pediatricians objective data they can review — critical for autism, motor, and language assessments.",
    ["Take 30-sec clips of each new skill.", "Save in a dated folder.", "Show the ped at next visit."],
    "Showed ped a video of unusual hand flapping → triggered earlier ASD eval.",
    "Verbal description — easily missed without video.",
    "Take one video today of any skill.",
    "1 min",
    "Wetherby A., Prizant B., First Words Project; CDC ASD Screening"),
];

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 9 — SEPARATION ANXIETY (INFANT)
// ═══════════════════════════════════════════════════════════════════════════
const SEPARATION_WINS: InfantWin[] = [
  w(1, "Understand the Developmental Window",
    "Separation anxiety means healthy attachment is forming.",
    "Object permanence develops 6–8 mo, peaks separation anxiety 8–18 mo. It's a sign of healthy bonding (Bowlby), not a problem to fix.",
    ["Read 1-page summary of object permanence.", "Reframe: this is bonding success, not failure.", "Tell yourself: 'this means she trusts me'."],
    "9-mo screaming at handoff → reframed as bonding milestone → handled it calmer.",
    "Treating it as a behavior problem — adds parent stress to baby's stress.",
    "Save the developmental window dates on calendar.",
    "5 min",
    "Bowlby J., Attachment and Loss (1969); Ainsworth M. (1978)"),
  w(2, "Practice Peek-a-Boo Daily",
    "The single best object-permanence practice game.",
    "Peek-a-boo teaches that disappeared = still exists. Builds the cognitive bridge for handling separation.",
    ["Play peek-a-boo 3× daily, varied formats.", "Hide behind hands, blanket, then doorway.", "Make it joyful with surprise + reunion."],
    "Daily peek-a-boo at 7 mo → smoother handoffs by 9 mo.",
    "Stopping when baby seems 'upset' — push gently through, joyful reunion teaches.",
    "Play 3 rounds today.",
    "5 min",
    "Piaget J., Object Permanence stages (1954); Munakata Y. (1994)"),
  w(3, "Use Short Repeated Goodbyes",
    "Short, frequent practice beats long avoidance.",
    "Practicing 5-min separations builds tolerance the way exposure therapy works for adults.",
    ["Step into another room for 1 min.", "Build to 5 min, then 10.", "Always return cheerfully."],
    "Daily 5-min 'mommy is in kitchen' practice → drop-offs improved in 2 weeks.",
    "Avoiding separations because they're hard — extends the phase.",
    "Practice one 5-min separation today.",
    "Daily",
    "Bowlby J., Strange Situation; Ainsworth M. (1978)"),
  w(4, "Create a Predictable Goodbye Ritual",
    "Same words + same actions = predictable = safe.",
    "Routines create predictability. A 30-second goodbye ritual lowers cortisol because the brain knows what comes next.",
    ["Pick 3 elements (hug, kiss, special phrase).", "Use it identically every goodbye.", "Keep total ritual under 1 min."],
    "Hug → kiss → 'Mommy comes back at lunch' → same words daily made the goodbye 50% smoother.",
    "Different goodbyes each day — adds uncertainty.",
    "Design your 3-step ritual today.",
    "5 min design",
    "Mindell J.A., Sleep Routines and Goodbye Routines (2009)"),
  w(5, "Don't Sneak Away",
    "One sneak-away erodes weeks of trust.",
    "Sneaking out teaches: 'they could disappear at any moment'. Result: more clinginess, more anxiety.",
    ["Always say goodbye, even if she cries.", "Make it brief but real.", "Leave once, don't return."],
    "Stopped sneaking out → 4 days of harder goodbyes → then much easier.",
    "Sneaking out 'to avoid drama' — increases drama long-term.",
    "Commit: no more sneak-aways from today.",
    "Per goodbye",
    "Bowlby J. (1969); Sroufe L.A., Attachment Across Lifespan (2005)"),
  w(6, "Leave with Familiar Caregiver",
    "Familiar = safe. New caregiver during peak phase = harder.",
    "8–18 mo is the worst window to introduce a new caregiver. If possible, transition new caregivers before or after this window.",
    ["For peak window: prefer known caregivers.", "If new caregiver needed, do 3+ overlap visits.", "Build familiarity with shared activity."],
    "Three overlap visits with new nanny → first solo handoff went smoothly.",
    "Day 1 cold drop with stranger — guarantees prolonged distress.",
    "Plan 3 overlap sessions with any new caregiver.",
    "1 week",
    "AAP Guidance on Childcare Transitions; Belsky J. (2001)"),
  w(7, "Bring a Transitional Object",
    "Loveys are externalized attachment.",
    "Winnicott (1953) showed transitional objects are healthy bridges to autonomy. Safe after 12 mo per AAP (no loose items in crib before).",
    ["Pick a small breathable lovey (after 12 mo).", "Carry it to all separations.", "Wash it weekly with the same soap (smell matters)."],
    "Same little blanket at every drop-off → cried 30 sec instead of 30 min.",
    "Switching loveys frequently — defeats the purpose.",
    "Choose a lovey today.",
    "5 min",
    "Winnicott D.W., Transitional Objects and Phenomena (1953)"),
  w(8, "Practice Mini-Separations at Home",
    "Build tolerance in low-stakes safe environment.",
    "In-home practice means the only variable is your absence — perfect controlled exposure.",
    ["Step into another room for 30 sec.", "Talk through the wall ('I'm right here').", "Build to 5 min over a week."],
    "Daily room-to-room practice → real goodbyes felt familiar by week 2.",
    "Only practicing separations in stressful real-world situations.",
    "Practice one 30-sec home separation today.",
    "5 min",
    "Bowlby J. (1969); Exposure-based attachment research"),
  w(9, "Stay Calm During Goodbyes",
    "Your face is her threat-detection system.",
    "Sorce et al. (1985) social referencing study: babies look at parent's face to decide if a situation is safe. Your tense face = scary situation.",
    ["Take a deep breath before goodbye.", "Smile genuinely (or pretend convincingly).", "Use upbeat tone even if sad inside."],
    "Practiced calm face → daughter copied calm → first goodbye without tears.",
    "Hugging too long with sad face — confirms the danger.",
    "Practice your goodbye face in a mirror.",
    "1 min",
    "Sorce J.F. et al., Dev Psychol (1985); Klinnert M.D. (1986)"),
  w(10, "Reunite with Connection First",
    "First 2 minutes of reunion set the day's tone.",
    "Polyvagal-informed parenting: reconnection through eye contact + slow movement repairs separation stress within minutes.",
    ["Get to baby's eye level.", "Hug for 2 full minutes (no phones).", "Narrate: 'Mommy is back, I missed you'."],
    "2-min full reconnection on every return → calmer afternoons.",
    "Returning straight to chores or phone — confirms separation feels.",
    "Plan tomorrow's reunion ritual.",
    "2 min",
    "Porges S.W., Polyvagal Theory; Tronick E.Z., Still-Face research"),
  w(11, "Avoid Long Drawn-Out Departures",
    "Brief is kind — long is cruel.",
    "Extended hugs and 'just one more kiss' tell baby: 'this is dangerous, we're prolonging it'. Brief confident exits work better.",
    ["Hug, ritual, 'see you later', leave.", "Total time: under 1 minute.", "Don't return if she cries — undoing trust."],
    "60-sec goodbye → 2-min cry → calm play. Vs 5-min goodbye → 20-min cry.",
    "Coming back 'just to check' — restarts the goodbye trauma.",
    "Time tomorrow's goodbye and keep under 1 min.",
    "Per goodbye",
    "Bowlby J. (1969); Ainsworth M. (1978)"),
  w(12, "Trust This Phase Will Pass",
    "Peak separation anxiety is a 6-month window, not forever.",
    "Develop sequence: 8 mo onset, peak 10–18 mo, fades 18–24 mo. Knowing the timeline transforms the experience.",
    ["Mark on calendar: 'expected fade window 18–24 mo'.", "Track weekly intensity — most see decline by 18 mo.", "Find one person in your life who's been through it."],
    "Knowing 'this will pass by 18 mo' helped survive the 11-mo peak.",
    "Believing 'she'll always be like this' — baby reads your hopelessness.",
    "Mark the expected fade window on your calendar.",
    "2 min",
    "Bowlby J., Attachment Phase Stages (1969); WHO Child Development"),
];

// ═══════════════════════════════════════════════════════════════════════════
// PROBLEM 10 — OVERSTIMULATION
// ═══════════════════════════════════════════════════════════════════════════
const OVERSTIM_WINS: InfantWin[] = [
  w(1, "Recognize the Signs",
    "Catch overstimulation in the first 30 seconds.",
    "Early signs: turning head away, arching back, glazed stare, grimacing. Late signs: crying, color change, full meltdown.",
    ["Memorize the 4 early signs.", "Scan baby every 5–10 min during stimulating activities.", "Act at the first early sign."],
    "Spotted head-turn at busy mall → moved to quiet alcove → meltdown avoided.",
    "Waiting for crying — the system is already overwhelmed by then.",
    "Practice scanning at next outing.",
    "Per outing",
    "Brazelton T.B., Neonatal Behavioral Assessment Scale; Als H. (1982)"),
  w(2, "Reduce Background Noise + TV",
    "Constant audio is invisible overstimulation.",
    "Christakis (2009): background TV reduces parent talk by 770 words/hour and increases infant cortisol. The 'no one's watching' TV is the worst.",
    ["Turn off background TV, music, podcasts.", "Use silence as default.", "Add audio intentionally only when baby is calm."],
    "Eliminated kitchen TV → baby's afternoon mood transformed in 3 days.",
    "Leaving TV on 'for company' — costs both speech and calm.",
    "Turn off background audio right now.",
    "1 min",
    "Christakis D.A. et al., Pediatrics (2009)"),
  w(3, "Cap Screen Time (AAP: 0 under 18 mo)",
    "Screens fundamentally overload infant nervous systems.",
    "AAP (2016, 2022): zero screens under 18 mo (except video calls). Screens deliver too much sensory input too fast for developing nervous systems.",
    ["Audit all baby screen exposure honestly.", "Eliminate or replace with face-to-face.", "Video calls with family are fine."],
    "Cut all screens → naps lengthened from 30 to 90 min within a week.",
    "Educational baby apps — same overstimulation as cartoons.",
    "Designate the next 24 hr screen-free.",
    "Daily",
    "AAP Media Use Guidelines (2016, 2022)"),
  w(4, "Limit Visitor Volume + Holding",
    "Ten people holding baby in two hours = system overload.",
    "Birthday parties, family gatherings, and visitor surges are the #1 cause of post-event meltdowns.",
    ["Set a max number of holders (e.g., 3).", "Take baby to a quiet room every 30 min.", "Leave events earlier than feels socially comfortable."],
    "Cousin's wedding — 30-min quiet breaks every hour → no meltdown.",
    "Letting everyone hold baby 'because it's once a year' — costs days of regulation.",
    "Plan a quiet break for next event.",
    "Per event",
    "Brazelton T.B., Touchpoints (2006); Greenspan S.I."),
  w(5, "Build Quiet Recovery Time After Outings",
    "1 hour of stimulation = 30+ min of recovery time.",
    "Nervous system needs as much downtime as upstime in early years. This is biology, not laziness.",
    ["Schedule 30-min quiet time after every outing.", "No screens, no music, no visitors.", "Floor play or rocking only."],
    "Built mandatory quiet hour after groceries → afternoon meltdowns ended.",
    "Stacking activities back-to-back — depletes regulation.",
    "Schedule recovery time after tomorrow's outing.",
    "Daily",
    "Greenspan S.I., The Child with Special Needs (1998)"),
  w(6, "Use Dim Lighting in Evening",
    "Bright lights after 6 PM suppress melatonin and amp the system.",
    "Chang (2015): blue light exposure suppresses melatonin 50%+. Even ceiling LEDs delay sleep onset and increase evening fussiness.",
    ["Switch to warm-tone bulbs (2700K).", "Dim ceiling lights to 30% after 6 PM.", "Use lamps instead of overheads in evening."],
    "Switched to warm dim lighting at 6 PM → bedtime resistance ended.",
    "Bright overhead lights through bedtime — overstimulates.",
    "Test your evening lighting tonight.",
    "10 min",
    "Chang A.M. et al., PNAS (2015) 112(4):1232"),
  w(7, "Wear Baby in a Wrap (Calming Pressure)",
    "Deep pressure + motion = the original swaddle.",
    "Wraps deliver continuous deep pressure to vestibular system, triggering calming reflex (Karp). Hands-free for parent and calming for baby.",
    ["Choose a stretchy wrap (Moby, Solly).", "Wrap snug but not restrictive.", "Walk gently — the slow movement compounds calm."],
    "Wrap on at fussy hour → calm in 8 min, slept 45 min in wrap.",
    "Loose wraps — no calming pressure benefit.",
    "Practice your wrap today.",
    "20 min",
    "Karp H., 5 S's; Hunziker U.A., Barr R.G., Pediatrics (1986)"),
  w(8, "Try Side-Lying or Rocking",
    "Vestibular input is a direct path to calm.",
    "Slow rocking activates the vestibular system, which has a direct neural connection to the parasympathetic (calming) branch.",
    ["Hold side-lying in your arms.", "Rock at ~60 BPM (slow heartbeat tempo).", "Add humming for compounded effect."],
    "60-BPM rocking with humming = calm in 90 sec.",
    "Fast rocking — engages alert system, opposite effect.",
    "Practice slow 60-BPM rocking today.",
    "5 min",
    "Porges S.W. (2011); Vestibular calming research"),
  w(9, "Do One Activity at a Time",
    "Multitasking environments overload baby's cortex.",
    "Christakis (2018): infants under 2 cannot filter sensory input — every input is processed equally. Multiple inputs = overwhelm.",
    ["Pick ONE: music, talking, OR play.", "Add second only when baby is calm.", "Eliminate background distractions during play."],
    "Quiet floor play (no music/no talk) → 25 min of focused exploration.",
    "Trying to play + music + chat at once — system shuts down.",
    "Pick one input for tomorrow's first play time.",
    "Per session",
    "Christakis D.A., Curr Probl Pediatr (2018)"),
  w(10, "Watch the 4–6 PM Dysregulation Window",
    "Plan around the predictable evening crash.",
    "Most babies hit a regulation low at 4–6 PM (cortisol shifts + day's accumulated stimulation). Plan for it.",
    ["Block 4–6 PM as low-stim time daily.", "Move errands and visits outside this window.", "Use the window for outdoor walk or quiet floor time."],
    "Moved errands to mornings → 4 PM became reliably calm.",
    "Scheduling activities into the 4–6 PM window.",
    "Audit your 4–6 PM tomorrow.",
    "Daily",
    "Brazelton T.B., Witching Hour Research"),
  w(11, "Create a Designated Calm Corner",
    "A physical 'reset zone' shortcuts regulation.",
    "A consistent calm space (low light, soft texture, no toys) trains the brain to associate it with regulation. Builds a self-soothing bridge.",
    ["Choose a small corner (closet, nursery alcove).", "Add: soft mat, dim lamp, one lovey.", "Use it daily for 15 min, even when calm."],
    "Daily 15-min calm corner time → baby goes there voluntarily by 14 mo.",
    "Only using it during meltdowns — it becomes a punishment cue.",
    "Set up your calm corner today.",
    "30 min",
    "Greenspan S.I.; Sensory integration practice"),
  w(12, "Practice Slow Pace (Parent-Led)",
    "Your pace becomes baby's pace — make yours intentional.",
    "Mirror neurons + co-regulation: babies sync to your physical rhythm. A frenetic parent = frenetic baby.",
    ["Walk at half speed during baby time.", "Speak slowly with pauses.", "Breathe out twice as long as in."],
    "Practiced slow-walking through morning routine → baby's morning fussiness ended.",
    "Multitasking with baby in tow — your stress transfers fully.",
    "Practice slow pace for 30 min tomorrow morning.",
    "Daily",
    "Iacoboni M., Mirror Neurons (2009); Porges S.W. (2011)"),
];

// ═══════════════════════════════════════════════════════════════════════════
// MAIN DATASET — 10 problems, each with 12 deep wins
// ═══════════════════════════════════════════════════════════════════════════
export const INFANT_PROBLEMS: InfantProblem[] = [
  {
    id: "baby-not-sleeping",
    emoji: "😴",
    title: { en: "Baby not sleeping", hi: "बच्चा सो नहीं रहा", hin: "Baby so nahi raha" },
    description: { en: "Trouble falling or staying asleep", hi: "सोने या सोते रहने में परेशानी", hin: "Sone ya sote rehne mein dikkat" },
    reason: {
      en: "Overtiredness, overstimulation, or irregular sleep timing.",
      hi: "अत्यधिक थकान, ज़्यादा उत्तेजना या असमान नींद का समय।",
      hin: "Bahut zyada thakaan, overstimulation ya irregular sleep timing.",
    },
    solution: [
      { en: "Follow a consistent sleep routine.", hi: "एक नियमित सोने की दिनचर्या अपनाएँ।", hin: "Ek consistent sleep routine follow karein." },
      { en: "Reduce noise and light before sleep.", hi: "सोने से पहले शोर और रोशनी कम करें।", hin: "Sone se pehle noise aur light kam karein." },
      { en: "Watch sleep cues like rubbing eyes.", hi: "आँख मलने जैसे नींद के संकेत देखें।", hin: "Aankh malne jaise sleep cues notice karein." },
    ],
    insight: {
      en: "Babies need predictable sleep patterns to feel secure.",
      hi: "बच्चों को सुरक्षित महसूस करने के लिए अनुमानित नींद के पैटर्न चाहिए।",
      hin: "Babies ko secure feel karne ke liye predictable sleep patterns chahiye.",
    },
    reassure: {
      en: "This is very common and improves with routine.",
      hi: "यह बहुत आम है और दिनचर्या से सुधर जाता है।",
      hin: "Yeh bahut common hai aur routine ke saath behtar ho jaata hai.",
    },
    rootCause: "Most infant sleep problems trace to one of three drivers: missed wake windows (overtiredness), inconsistent sleep cues, or strong sleep-onset associations that recreate at every cycle transition.",
    summary: "These 12 wins combine the AAP safe-sleep framework, the Karp 5 S's, and the Mindell/Weissbluth research on routine and timing. Apply them in order over 7–14 nights.",
    wins: SLEEP_WINS,
  },
  {
    id: "excessive-crying",
    emoji: "😭",
    title: { en: "Excessive crying", hi: "बहुत ज़्यादा रोना", hin: "Bahut zyada rona" },
    description: { en: "Long or frequent crying spells", hi: "लंबे या बार-बार रोने के दौरे", hin: "Lambe ya baar-baar crying spells" },
    reason: {
      en: "Hunger, discomfort, tiredness, or need for attention.",
      hi: "भूख, असुविधा, थकान या ध्यान की ज़रूरत।",
      hin: "Bhookh, discomfort, thakaan ya attention ki zarurat.",
    },
    solution: [
      { en: "Check feeding and diaper first.", hi: "सबसे पहले दूध और डायपर देखें।", hin: "Pehle feeding aur diaper check karein." },
      { en: "Try gentle rocking or holding.", hi: "धीरे से झुलाएँ या गोद में लें।", hin: "Halke se jhulayein ya god mein lein." },
      { en: "Use a calm voice and eye contact.", hi: "शांत आवाज़ और आँखों से संपर्क रखें।", hin: "Shaant awaaz aur eye contact use karein." },
    ],
    insight: {
      en: "Crying is the baby's main way to communicate.",
      hi: "रोना बच्चे का बात करने का मुख्य तरीका है।",
      hin: "Rona baby ka main communicate karne ka tareeka hai.",
    },
    reassure: {
      en: "You are doing the right thing by responding calmly.",
      hi: "शांति से जवाब देकर आप सही कर रहे हैं।",
      hin: "Calmly respond karke aap sahi kar rahe hain.",
    },
    rootCause: "Most excessive crying falls within the normal PURPLE crying curve (peak at 6 weeks). The remaining 5–10% is a treatable cause: reflux, allergy, ear infection, or unmet basic need.",
    summary: "These 12 wins combine Karp's 5 S's, Hunziker's babywearing research, the PURPLE crying framework, and AAP/CDC parental-burnout safety guidance. They're ordered: rule out → soothe → identify → protect yourself.",
    wins: CRYING_WINS,
  },
  {
    id: "feeding-issues",
    emoji: "🍼",
    title: { en: "Feeding issues", hi: "दूध पीने की समस्या", hin: "Feeding ki problem" },
    description: { en: "Refusing or struggling with feeds", hi: "दूध पीने से इंकार या कठिनाई", hin: "Feed lene se mana ya dikkat" },
    reason: {
      en: "Growth phase changes or distraction.",
      hi: "वृद्धि चरण में बदलाव या ध्यान भटकना।",
      hin: "Growth phase changes ya distraction.",
    },
    solution: [
      { en: "Feed in a calm environment.", hi: "शांत माहौल में दूध पिलाएँ।", hin: "Calm environment mein feed karein." },
      { en: "Keep feeding timing consistent.", hi: "दूध पिलाने का समय नियमित रखें।", hin: "Feeding timing consistent rakhein." },
      { en: "Avoid force feeding.", hi: "ज़बरदस्ती न खिलाएँ।", hin: "Force feeding avoid karein." },
    ],
    insight: {
      en: "Appetite varies during development phases.",
      hi: "विकास के दौरान भूख बदलती रहती है।",
      hin: "Development phases mein appetite badalti rehti hai.",
    },
    reassure: {
      en: "Small changes in feeding are normal.",
      hi: "खाने में छोटे बदलाव सामान्य हैं।",
      hin: "Feeding mein chote changes normal hain.",
    },
    rootCause: "Feeding issues usually stem from one of: mechanical (latch/flow), environmental (distraction), developmental (3–5 mo socially aware phase), or rarely, medical (CMPA/reflux).",
    summary: "These 12 wins follow the responsive-feeding framework (Pérez-Escamilla 2017) plus WHO/AAP guidance. Read cues, check mechanics, control environment, then escalate to medical if symptoms persist.",
    wins: FEEDING_WINS,
  },
  {
    id: "teething-discomfort",
    emoji: "🦷",
    title: { en: "Teething discomfort", hi: "दांत निकलने की तकलीफ", hin: "Teething ki takleef" },
    description: { en: "Sore gums and fussiness", hi: "मसूड़ों में दर्द और चिड़चिड़ापन", hin: "Mason mein dard aur chidchidapan" },
    reason: {
      en: "Emerging teeth causing gum irritation.",
      hi: "नए दांत आने से मसूड़ों में जलन।",
      hin: "Naye teeth aane se gum irritation.",
    },
    solution: [
      { en: "Use clean teething toys.", hi: "साफ टीथिंग खिलौने दें।", hin: "Clean teething toys dein." },
      { en: "Gently massage the gums.", hi: "मसूड़ों की हल्की मालिश करें।", hin: "Gums ki halki maalish karein." },
      { en: "Offer cold (not frozen) items.", hi: "ठंडी (जमी हुई नहीं) चीज़ें दें।", hin: "Thandi (frozen nahi) cheezein offer karein." },
    ],
    insight: {
      en: "Teething can cause mild discomfort and irritability.",
      hi: "दांत निकलने से हल्की तकलीफ़ और चिड़चिड़ापन हो सकता है।",
      hin: "Teething se halki discomfort aur irritability ho sakti hai.",
    },
    reassure: {
      en: "This phase will pass soon.",
      hi: "यह दौर जल्द ही गुज़र जाएगा।",
      hin: "Yeh phase jaldi guzar jayega.",
    },
    rootCause: "Teething pain comes from gum tissue stretching as teeth erupt. Counter-pressure (chewing, massage) and cold are the only proven non-pharmacological interventions.",
    summary: "These 12 wins combine AAPD eruption-chart guidance, FDA safety warnings on numbing gels, and proven counter-pressure + cold relief tactics. Distinguish teething from illness, then soothe.",
    wins: TEETHING_WINS,
  },
  {
    id: "not-eating-solids",
    emoji: "🥄",
    title: { en: "Not eating solids", hi: "ठोस आहार न खाना", hin: "Solid food nahi khaa raha" },
    description: { en: "Refusing new textures of food", hi: "नए स्वाद-बनावट से इंकार", hin: "Naye textures se mana karna" },
    reason: {
      en: "Adjustment phase to new textures.",
      hi: "नई बनावट के साथ ढलने का समय।",
      hin: "Naye textures ke saath adjust hone ka phase.",
    },
    solution: [
      { en: "Introduce slowly.", hi: "धीरे-धीरे शुरू करें।", hin: "Dheere-dheere introduce karein." },
      { en: "Repeat foods multiple times.", hi: "एक ही खाना कई बार दें।", hin: "Same food multiple times repeat karein." },
      { en: "Do not pressure the child.", hi: "बच्चे पर दबाव न डालें।", hin: "Bachhe par pressure mat daalein." },
    ],
    insight: {
      en: "Babies need time to accept new foods.",
      hi: "बच्चों को नए खाने को अपनाने में समय लगता है।",
      hin: "Babies ko naye foods accept karne mein time lagta hai.",
    },
    reassure: {
      en: "Repetition helps acceptance.",
      hi: "दोहराने से स्वीकार्यता बढ़ती है।",
      hin: "Repetition se acceptance badhti hai.",
    },
    rootCause: "Solid refusal usually traces to: starting before readiness signs, insufficient repeat exposure (8–15 times needed), texture progression too slow or too fast, or pressure-feeding patterns.",
    summary: "These 12 wins combine the Maier exposure research, LEAP allergen guidance, Satter feeding division of responsibility, and Brown's BLW evidence. Build acceptance over weeks, not days.",
    wins: SOLIDS_WINS,
  },
  {
    id: "frequent-night-waking",
    emoji: "🌙",
    title: { en: "Frequent night waking", hi: "बार-बार रात में उठना", hin: "Raat mein baar-baar uthna" },
    description: { en: "Waking multiple times at night", hi: "रात में कई बार जागना", hin: "Raat mein kai baar jaagna" },
    reason: {
      en: "Sleep cycle transitions or hunger.",
      hi: "नींद के चरण बदलना या भूख।",
      hin: "Sleep cycle transitions ya bhookh.",
    },
    solution: [
      { en: "Keep the night environment calm.", hi: "रात का माहौल शांत रखें।", hin: "Raat ka environment calm rakhein." },
      { en: "Avoid stimulation during the night.", hi: "रात में उत्तेजना से बचें।", hin: "Raat mein stimulation avoid karein." },
      { en: "Maintain a consistent bedtime.", hi: "सोने का समय नियमित रखें।", hin: "Bedtime consistent rakhein." },
    ],
    insight: {
      en: "Night waking is normal in early development.",
      hi: "शुरुआती विकास में रात में जागना सामान्य है।",
      hin: "Early development mein night waking normal hai.",
    },
    reassure: {
      en: "Sleep improves gradually.",
      hi: "नींद धीरे-धीरे बेहतर होती है।",
      hin: "Neend dheere-dheere behtar hoti hai.",
    },
    rootCause: "Frequent night wakes after 6 mo are usually habit + sleep crutches, not hunger. Babies recreate the conditions they fell asleep in (rocking, feeding) at every sleep-cycle transition.",
    summary: "These 12 wins combine Mindell's behavioral sleep research, Pantley's gentle protocols, and AAP safe-sleep environment guidance. Address crutches and timing first, train responses second.",
    wins: NIGHT_WAKING_WINS,
  },
  {
    id: "always-irritable",
    emoji: "😣",
    title: { en: "Baby always irritable", hi: "बच्चा हमेशा चिड़चिड़ा", hin: "Baby hamesha irritable" },
    description: { en: "Frequent fussiness or upset mood", hi: "बार-बार चिड़चिड़ापन या ख़राब मूड", hin: "Baar-baar fussy ya upset mood" },
    reason: {
      en: "Overstimulation or tiredness.",
      hi: "ज़्यादा उत्तेजना या थकान।",
      hin: "Overstimulation ya thakaan.",
    },
    solution: [
      { en: "Reduce noise and screen exposure.", hi: "शोर और स्क्रीन कम करें।", hin: "Noise aur screen exposure kam karein." },
      { en: "Follow a routine.", hi: "एक दिनचर्या अपनाएँ।", hin: "Routine follow karein." },
      { en: "Give quiet time.", hi: "शांत समय दें।", hin: "Quiet time dein." },
    ],
    insight: {
      en: "Babies need calm environments to regulate emotions.",
      hi: "भावनाओं को संभालने के लिए बच्चों को शांत माहौल चाहिए।",
      hin: "Emotions regulate karne ke liye babies ko calm environment chahiye.",
    },
    reassure: {
      en: "This is manageable with small changes.",
      hi: "छोटे बदलावों से यह संभल जाता है।",
      hin: "Chote changes se yeh manageable hai.",
    },
    rootCause: "Persistent irritability traces to one of six causes: sensory overload (most common), unmet basic needs, hidden discomfort (reflux/ear/allergies), screen exposure, transition surprise, or temperament-input mismatch.",
    summary: "These 12 wins combine Christakis's screen research, Dunn's sensory profile work, Porges's polyvagal co-regulation, and AAP anticipatory guidance. Audit input before adding interventions.",
    wins: IRRITABLE_WINS,
  },
  {
    id: "not-reaching-milestones",
    emoji: "🌱",
    title: { en: "Not reaching milestones", hi: "मील के पत्थर तक नहीं पहुँचना", hin: "Milestones tak nahi pahunch raha" },
    description: { en: "Slower growth signs or skills", hi: "धीमी विकास संकेत या कौशल", hin: "Slow development signs ya skills" },
    reason: {
      en: "Natural variation in development pace.",
      hi: "विकास की गति में स्वाभाविक अंतर।",
      hin: "Development pace mein natural variation.",
    },
    solution: [
      { en: "Encourage daily play.", hi: "रोज़ खेल को बढ़ावा दें।", hin: "Roz play encourage karein." },
      { en: "Give tummy time.", hi: "टमी टाइम दें।", hin: "Tummy time dein." },
      { en: "Interact frequently.", hi: "बार-बार बातचीत करें।", hin: "Frequently interact karein." },
    ],
    insight: {
      en: "Each baby develops at their own pace.",
      hi: "हर बच्चा अपनी गति से विकसित होता है।",
      hin: "Har baby apni pace par develop karta hai.",
    },
    reassure: {
      en: "Observe gently, avoid panic.",
      hi: "धीरे से देखें, घबराएँ नहीं।",
      hin: "Gently observe karein, panic mat karein.",
    },
    rootCause: "Most milestones fall within a wide normal range (e.g., walking 8.5–17.6 mo). True developmental delay affects ~12% of children and benefits enormously from early intervention before age 3.",
    summary: "These 12 wins combine WHO milestone ranges, AAP Bright Futures screening schedule, the 2022 CDC milestone update, and IDEA Part C early-intervention pathways. Stimulate, screen, and refer if concerned.",
    wins: MILESTONE_WINS,
  },
  {
    id: "separation-anxiety-infant",
    emoji: "🫂",
    title: { en: "Separation anxiety", hi: "अलग होने की चिंता", hin: "Separation anxiety" },
    description: { en: "Distress when parent leaves", hi: "माता-पिता के जाने पर परेशानी", hin: "Parent ke jaane par pareshaani" },
    reason: { en: "Attachment development.", hi: "लगाव का विकास।", hin: "Attachment ka development." },
    solution: [
      { en: "Practice short separations.", hi: "छोटे अलगाव का अभ्यास करें।", hin: "Chote separations practice karein." },
      { en: "Reassure before leaving.", hi: "जाने से पहले आश्वासन दें।", hin: "Jaane se pehle reassure karein." },
      { en: "Return with calm behavior.", hi: "शांत व्यवहार के साथ लौटें।", hin: "Calm behavior ke saath wapas aayein." },
    ],
    insight: { en: "This shows strong bonding.", hi: "यह मज़बूत लगाव दिखाता है।", hin: "Yeh strong bonding dikhata hai." },
    reassure: { en: "This phase is temporary.", hi: "यह दौर अस्थायी है।", hin: "Yeh phase temporary hai." },
    rootCause: "Separation anxiety is a normal Bowlby attachment phase: object permanence develops 6–8 mo, peaks 8–18 mo, fades by 24 mo. Healthy attachment IS the cause — it's a sign things are going right.",
    summary: "These 12 wins draw on Bowlby/Ainsworth attachment research, Sorce's social-referencing studies, and Winnicott's transitional-object framework. Build tolerance through practice; never sneak away.",
    wins: SEPARATION_WINS,
  },
  {
    id: "overstimulation",
    emoji: "🌀",
    title: { en: "Overstimulation", hi: "अधिक उत्तेजना", hin: "Overstimulation" },
    description: { en: "Too much input at once", hi: "एक साथ बहुत कुछ", hin: "Ek saath bahut kuch" },
    reason: {
      en: "Too much noise, activity, or screen exposure.",
      hi: "बहुत ज़्यादा शोर, गतिविधि या स्क्रीन।",
      hin: "Bahut zyada noise, activity ya screen exposure.",
    },
    solution: [
      { en: "Reduce environment stimulation.", hi: "माहौल की उत्तेजना कम करें।", hin: "Environment stimulation kam karein." },
      { en: "Create a calm routine.", hi: "एक शांत दिनचर्या बनाएँ।", hin: "Calm routine banayein." },
      { en: "Use soft lighting.", hi: "मद्धम रोशनी रखें।", hin: "Soft lighting use karein." },
    ],
    insight: {
      en: "Babies process limited stimulation at a time.",
      hi: "बच्चे एक समय में सीमित उत्तेजना संभाल पाते हैं।",
      hin: "Babies ek time par limited stimulation process karte hain.",
    },
    reassure: {
      en: "A calm environment helps regulation.",
      hi: "शांत माहौल नियमन में मदद करता है।",
      hin: "Calm environment regulation mein help karta hai.",
    },
    rootCause: "Infant nervous systems process roughly 1/5 the sensory input adults handle. Modern environments (screens, background noise, packed schedules) chronically exceed that capacity.",
    summary: "These 12 wins combine Brazelton/Als signs of dysregulation, AAP screen guidance, Karp's wrap/wear research, and Greenspan's calm-corner sensory-integration approach. Subtract input, then add deep-pressure soothing.",
    wins: OVERSTIM_WINS,
  },
];

// ─── Public helpers ────────────────────────────────────────────────────────
export const INFANT_PROBLEM_IDS: ReadonlySet<string> = new Set(
  INFANT_PROBLEMS.map((p) => p.id),
);

export function isInfantProblemId(id: string | null | undefined): boolean {
  return !!id && INFANT_PROBLEM_IDS.has(id);
}

export function getInfantProblem(id: string): InfantProblem | undefined {
  return INFANT_PROBLEMS.find((p) => p.id === id);
}

export function pickLang(text: LocalizedText, lang: string | undefined): string {
  const code = normalizeLang(lang);
  return text[code];
}

export function normalizeLang(lang: string | undefined): Lang {
  if (!lang) return "en";
  const l = lang.toLowerCase();
  if (l === "hin" || l.startsWith("hinglish")) return "hin";
  if (l.startsWith("hi")) return "hi";
  return "en";
}
